### ISSUE TITLE
ACL ARR Area Chair: Display all reviewers by default

### ISSUE THREAD

**Issue by habernal** [openreview/openreview#10]
**Is your feature request related to a problem? Please describe.**
Currently in the Area Chair console (ACL ARR), reviewers for each paper are shown after clicking on "Show reviewer" at each paper. Slows down searching for particular reviewers (who is doing what), on needs to click through all the papers to find out which reviewers are which papers; with 10 papers it gets very annoying).

**Describe the solution you'd like**
Just show the reviewers unfolded by default.

**Describe alternatives you've considered**
Enable searching by reviewers (name and e-mail) in the search form.

**Additional context**
Text search using browser doesn't work, as the content is perhaps AJAX-rendered?

**Comment by melisabok** [comment]
I think a good solution for this is to enable the search textbox in the AC console, what do you think? @xkopenreview 

Showing all reviewers by default can make the rows have different heights, I'm not sure how it looks like.

**Comment by xkopenreview** [comment]
Hi Ivan
you can search reviewer name and email using the search box but in query search mode
it will switch to query search mode when you enter + in the search box

i added two examples to search reviewer by name and email

<img width="761" alt="image" src="https://user-images.githubusercontent.com/60613434/156243344-6646b05d-37e6-4f0b-847f-af0e7bc68185.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/60613434/156243488-9610e05b-3942-4756-9505-5f80e6587451.png">

if you hover over the info icon, you will see the list of fields available and some instructions for using the query search

**Comment by habernal** [comment]
@xkopenreview Just tried out, very nice feature, thank you!
