### ISSUE TITLE
regex must be a prefix regex. If validation passes ...

### ISSUE THREAD

**Issue by MarvinT** [openreview/openreview#100]
**Describe the bug**
Cross posting https://github.com/openreview/openreview-py/issues/1762 here since it impacts some of the web uis as well

**To Reproduce**
I also noticed this breaks lots of openreview sites
[google search that shows examples](https://www.google.com/search?q=openreview+regex+must+be+a+prefix+regex.+If+validation+passes%2C+any+remaining+regex+characters+will+be+escaped)
https://openreview.net/group?id=NeurIPS.cc/2021/Workshop/ImageNet_PPF
https://openreview.net/group?id=thecvf.com/ICCV/2019/Workshop/Pre-Reg
https://openreview.net/group?id=roboticsfoundation.org/RSS/2022/Workshop/L-DOD
https://openreview.net/group?id=EMNLP/2019/Workshop/Summarization

**Expected behavior**
Loading the submissions

**Screenshots**
![image](https://github.com/openreview/openreview/assets/1386198/2dd41537-0512-457f-bc83-2143bd9012f8)

**Device information (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 114

**Additional context**
see https://github.com/openreview/openreview-py/issues/1762

**Comment by carlosmondra** [comment]
Closing as it seems to have been resolved here https://github.com/openreview/openreview-py/issues/1762
