### ISSUE TITLE
Secondary reviewer

### ISSUE THREAD

**Issue by jmp84** [openreview/openreview#106]
**Is your feature request related to a problem? Please describe.**

At EMNLP 2023 we're getting many requests from reviewer to delegate reviews to secondary reviewers.
We've been doing manual reassignments which is time consuming.

**Describe the solution you'd like**

It'd be great if reviewers can manage this themselves. For example, there is no official reassignment but the reviewer can add an additional reviewer, mark them as secondary, so they are acknowledged.

**Describe alternatives you've considered**

Alternatively, ACs could manage this but I don't think ACs can add reviewers to the system.

**Additional context**

N/A

**Comment by melisabok** [comment]
This issue is duplicated: https://github.com/openreview/openreview/issues/93

**Comment by melisabok** [comment]
> Alternatively, ACs could manage this but I don't think ACs can add reviewers to the system.

It depends on the venue but AC can change reviewer assignments.

**Comment by jmp84** [comment]
AC can change reviewer assignments but cannot add reviewers to the system (?)

**Comment by melisabok** [comment]
Yes, they can recruit external reviewers. But this depends on the venue configuration.

**Comment by melisabok** [comment]
Closing this issue because it is duplicated
