### ISSUE TITLE
Error: rebuttal value must NOT have more than 6000 characters

### ISSUE THREAD

**Issue by toosi** [openreview/openreview#107]
**Describe the bug**
Even though the character count shows 6 characters remaining, I get 
Error: rebuttal value must NOT have more than 6000 characters
when I try to submit.

**To Reproduce**
1. Go to  openreview and write in rebuttal (general rebuttal panel) and write 5994 characters.
2. Click on submit
3. See error

**Expected behavior**
Succesful submission

**Screenshots**

**Device information (please complete the following information):**
 - OS: iOS
 - Browser chrome

![image](https://github.com/openreview/openreview/assets/6719395/e15d9532-958f-41ed-800f-443dd3d9ecd2)

**Comment by carlosmondra** [comment]
@toosi thanks for reporting this issue. Would you mind sending us an email to info@openreview.net with the link to the rebuttal comment that was failing? I know that the rebuttal you posted does not fail, but it may help us reproduce the bug more easily. Thanks!

**Comment by toosi** [comment]
@carlosmondra Thank you for your response. I sent the link to the address above.

Thanks.

**Comment by carlosmondra** [comment]
The issue has been fixed with PR https://github.com/openreview/openreview-web/pull/1583.

Please reopen if issue persists.
