### ISSUE TITLE
Show "Your Active Consoles" in reverse chronological order

### ISSUE THREAD

**Issue by habernal** [openreview/openreview#11]
**Is your feature request related to a problem? Please describe.**
As ACL ARR has so many "venues" (each month 1. reviewer, 2. author, 3. area editor), the active consoles are actually not "active" anymore, e.g., from 2021 July, etc. Navigating to the current ones (where one needs to write a review or chair an area) need extra steps (scroll down, click on "Show all XX venues", scroll again). Cumbersome. See the screenshot.

**Describe the solution you'd like**
Show venues in reverse chronological order, so the most current ones are at the top.

**Describe alternatives you've considered**
Mark a venue as "inactive", but that would be perhaps not easy to implement (managing states of venues for each user).

**Additional context**
![Bildschirmfoto_2022-02-16_20-44-57](https://user-images.githubusercontent.com/11850778/154344611-6e6cefb2-772f-4040-8e53-642b35208934.png)

**Comment by melisabok** [comment]
I think the solution here is to remove the inactive venues from the list. @nlbahy can you remove the old iterations of ARR from the active_venues group?

**Comment by nlbahy** [comment]
Fixed! I removed all inactive venues from the active venues group.
