### ISSUE TITLE
(Minor) Random order in Reviewer properties

### ISSUE THREAD

**Issue by manuelhaussmann** [openreview/openreview#110]
**Describe the bug**
The description in the order of reviewer properties (Affinity score, pending reviews,...) is not consistent between reviewers. (See the screenshot below for an example)

**To Reproduce**
Visual inspection of the reviewer assignment console. 

**Expected behavior**
Have all of them in a consistent order.

**Screenshots**
![order_of_files](https://github.com/openreview/openreview/assets/1485045/655c8d5a-2694-4a66-bf90-b627c5c0ffea)

**Comment by melisabok** [comment]
Hi Manuel, the UI has a way to order the reviewers by different edge types like: affinity scores, conflict, etc. 

Which order are you expecting here?

**Comment by manuelhaussmann** [comment]
In this case I sorted the reviewers by affinity score (I should have mentioned that). But then within this sorting we see that for the five properties each reviewer posses, e.g., the _Custom Max Papers_ property, reviewer 1 has it listed as the third property, for Reviewer 2 the last and for reviewer 3 the fourth. It would be helpful if, conditioned on the property the reviewers are ordered by, the remaining four properties are listed, e.g., in an alphabetical order.
