### ISSUE TITLE
I can't verify email from  noreply@openreview.net.

### ISSUE THREAD

**Issue by johnlegend429** [openreview/openreview#111]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device information (please complete the following information):**
 - OS: [e.g. iOS, Windows 10]

**Additional context**

**Comment by johnlegend429** [comment]
I can't get verify email from noreply@openreview.net.
How long I have to wait?

**Comment by melisabok** [comment]
please send us an email at info@openreview.net so we can take a look at your case, thanks.

**Comment by carlosmondra** [comment]
Closing, as this is requires sharing personal information.
Please refer to the [guidelines](https://github.com/openreview/openreview/blob/main/CONTRIBUTING.md)

**Comment by johnlegend429** [comment]
sorry. I signed up with wrong email. my real email is
***@***.***
could you change it?
