### ISSUE TITLE
Error when submitting paper due to invalid reviewer nomination

### ISSUE THREAD

**Issue by dirmeier** [openreview/openreview#112]
**Describe the bug**

Hello, when trying to submit a manuscript often suggesting an author as a reviewer is required. When doing so, i.e., when entering the mail I am registered with in the designated field, I am currently receiving the following error:

```
Error: The path 2/content/authorids/value defined in invitation/edit/note/content/reviewer_nomination/readers/1 is invalid: 
The path 2/content/authorids/value does not resolve to any value.
```

I believe this might be a bug as I am not able to submit a paper.

Thanks,
Simon

**Comment by melisabok** [comment]
This is related to a misconfiguration of the program chairs of the venue, please send us an email at info@openreview.net so we can investigate.

**Comment by dirmeier** [comment]
Great, thanks!
