### ISSUE TITLE
Could not update my submission for ICLR2024 now.

### ISSUE THREAD

**Issue by lebronlambert** [openreview/openreview#114]
**Describe the bug**
I have the account with my email. When I registered for the openreview, I got confused with my first name and last name, then I made it right. However, now, I could not get my submission updated due to the problem (the author name does not match with the original one.)

**To Reproduce**
-

**Expected behavior**
I want to update my submission.

**Screenshots**
-

**Device information (please complete the following information):**
-

**Additional context**
-

**Comment by lebronlambert** [comment]
I change the name back to the worng one. Now it worked. I will use this wrong name until everythng is done.

**Comment by racheljsmart** [comment]
This issue was address via email. @lebronlambert are you still using the incorrect name?

**Comment by lebronlambert** [comment]
Yes, I am still using my wrong name now. I think I will wait unitl the rebuttal is done for ICLR2024. Then I will change back to my correct name.

**Comment by carlosmondra** [comment]
Please reopen if the issue persists
