### ISSUE TITLE
OpenReview should warn when adding a co-author without an active OpenReview profile

### ISSUE THREAD

**Issue by krzentner** [openreview/openreview#115]
**Is your feature request related to a problem? Please describe.**
My advisor has multiple OpenReview profiles, one of which is not active and cannot be used ([here](https://openreview.net/profile?id=~Gaurav_Sukhatme1)). When selecting authors, OpenReview still suggests using the broken profile, even though accessing that profile shows an error page (Error 400). 

**Describe the solution you'd like**
I would like OpenReview to not recommend broken profiles, and warn when a profile that is not active is added to a submission. In other words, if opening the profile for an author would show an error page, adding them to a submission should show a warning in the submission page.

**Describe alternatives you've considered**
Alternatively, provide a way for users to delete inactive profiles, so that this issue can be avoided in the future. I don't see any drawback to implementing this feature, if doing so is not unusually difficult.

**Comment by melisabok** [comment]
I think we should show the status of the profile when searching them. We can not filter them out because during a deadline some users may have issues activating their profiles and they can not be added as co-authors.

@xkopenreview @carlosmondra what do you think about showing the status of the profiles in the profile search result?

**Comment by carlosmondra** [comment]
All profiles have a `state` property that indicates the state of the profile (e.g. `state: "Active"` and this property is returned when doing a profile search. I like the idea of displaying the state of the profile while searching co-authors. Although, I'm not sure if authors will understand the different states of the profile. I do see people asking "What does `{ state: "Inactive" }` mean?". So we need to figure out a way to make this clear in the UI.

**Comment by melisabok** [comment]
the author console shows a green icon when the profile is active and red icon when it is not, so we can use the same icon in the profile search.

**Comment by krzentner** [comment]
At least in my use case, a message like "This user has not activated their profile yet." would prevent a lot of headache, and would hopefully be clear to most users. Thank you for looking into implementing this.

**Comment by melisabok** [comment]
This is fixed now.
