### ISSUE TITLE
Impossible to import DBLP publications

### ISSUE THREAD

**Issue by pys** [openreview/openreview#116]
**Describe the bug**
If there is a mistake in your DBLP name, it is Impossible to import DBLP publications

**To Reproduce**
1. Enter the DBLP permanent URL of a person with a mistake in DBLP name (such as me).
2. Click 'Add DBLP Papers to profile'.
4. The following error message appears 
---
Your OpenReview profile must contain the EXACT name used in your DBLP papers.

Should any of the following names be added to your profile?

Pierre-Yves Schobbens
Your current names are listed below:

Pierre Yves Schobbens
---
5. Try to click on the 'Add to your Profile' button : it does not work.

**Expected behavior**
I expect the button at step 5. to import the publications from my DBLP profile.

**Screenshots**
![Capture d’écran 2023-09-29 à 18 51 24](https://github.com/openreview/openreview/assets/1058006/6eecf14f-46d0-462d-9208-c20a5239b50c)

**Device information (please complete the following information):**
 - OS: MacOS 14.0 (23A344)
 - Browser: safari
 - Version: 17.0 (19616.1.27.211.1)
 But the same error appears on all browsers and OS.

**Context**
https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by pys** [comment]
Note that my DBLP name is in some sense correct: it is the name my parents intended to give me, and that has been wrongly written down by the public officer. Since then, I have to go by that name. By the way, my official name is:
Pierre Yves François Marie Joseph Schobbens
so the above is just an abbreviation. Actually it is too long to fit in the state computers, so my official name is not accessible to any officer or civil servant, unless they go to the papers records of the time.

**Comment by carlosmondra** [comment]
Seems like the DBLP submissions have been imported. Also, if you feel like it, you should now be able to enter your fullname if you are interested.
Please feel free to reopen the issue.

**Comment by pys** [comment]
Thanks!
