### ISSUE TITLE
Cannot submit camera ready version to EMNLP 2023

### ISSUE THREAD

**Issue by ahazeemi** [openreview/openreview#117]
**Describe the bug**
I cannot submit camera-ready version to EMNLP 2023 through ARR.

**To Reproduce**
1. Go to an accepted ARR EMNLP 2023 paper.
2. Click 'Edit -> Camera Ready Revision'
3. Upload pdf and submit.

**Expected behavior**
The camera-ready version should submit successfully.

**Screenshots**
<img width="1151" alt="Screenshot 2023-10-17 at 12 46 43 AM" src="https://github.com/openreview/openreview/assets/16561118/6387538f-04c7-4380-be8f-20f0719469e5">

**Device information (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version: 118.0.5993.70

**Comment by melisabok** [comment]
Thanks for reporting this, could you please send us an email at info@openreview.net with your paper number and title and we can take a look?
