### ISSUE TITLE
Can not submit camera ready revision

### ISSUE THREAD

**Issue by board1** [openreview/openreview#118]
![32ec924ad9d4c57ba500827e48ba27b](https://github.com/openreview/openreview/assets/37523042/6c170045-a569-4082-813d-edb88e26347c)

I choosed all the checkboxs, but I can not submit it, and meet this error

**Comment by Jiaxin-Wen** [comment]
same issue.

I check the source code, and find it is still as follows:
<img width="1077" alt="58fa40b891b34839de8150453349845" src="https://github.com/openreview/openreview/assets/48146603/74f02713-a1f4-42f0-a0b1-c33f4325dcc1">
<img width="634" alt="db2b00b26d9556f65d792a5b386dfa1" src="https://github.com/openreview/openreview/assets/48146603/9b3958cd-0fb4-4c5a-a40d-5424332fb8a6">
