### ISSUE TITLE
[UI/UX] Small title "Edge Browser" is confusing

### ISSUE THREAD

**Issue by habernal** [openreview/openreview#12]
**Describe the bug**
In the ACL ARR area chair console, there is a small bold title that reads "Edge Browser:" followed by a link to a page where one can re-assign reviewers. Not a native speaker, but I don't understand what "Edge Browser" means here (I guess it's not the MS Edge web-browser).

**Expected behavior**
Either remove completely (if it has no meaning), or rename to something unambiguous (maybe "Review assignment actions" if there are more actions for other roles?)

**Screenshots**
![Bildschirmfoto_2022-02-16_20-54-38](https://user-images.githubusercontent.com/11850778/154346163-da620892-2b8f-4a9b-9a62-066a91914eb4.png)

**Comment by melisabok** [comment]
I think we should remove the "Edge Browser" text.

**Comment by carlosmondra** [comment]
Fixed here: https://github.com/openreview/openreview-py/pull/1145
