### ISSUE TITLE
Errors on default templates for meta-review in documentation

### ISSUE THREAD

**Issue by adinriv** [openreview/openreview#121]
**Describe the bug**
The meta-review default template for API v2 is not working out of the box.

**To Reproduce**
1. Go to [default meta-review form](https://docs.openreview.net/reference/default-forms/default-meta-review-form)
2. Copy API v2 JSON
3. Paste it in the meta-review field to configure the form in a venue
4. See error https://api.openreview.net/references?id=-N-JjV9mJC

**Expected behavior**
The meta-review template should work out of the box and provide the same behavior as in the current setup.

**Device information (please complete the following information):**
 - OS: Ubuntu 23.04
 - Browser Firefox
 - Version  118.0.2 (64-bit)

**Additional context**
The solution was to add the `input` field (and replace `"type": "select"` with `input`) with  to the form and the error went away.
```
{
  "metareview": {
    "value": {
      "param": {
        "type": "string",
        "minLength": 1,
        "maxLength": 5000,
        "input": "textarea",
        "markdown": true
      }
    },
    "order": 1,
    "description": "Please provide an evaluation of the quality, clarity, originality and significance of this work, including a list of its pros and cons. Your comment or reply (max 5000 characters). Add formatting using Markdown and formulas using LaTeX. For more information see https://openreview.net/faq"
  },
  "recommendation": {
    "value": {
      "param": {
        "type": "string",
        "enum": [
          "Accept (Oral)",
          "Accept (Poster)",
          "Reject"
        ],
        "input": "select"
      }
    },
    "order": 2
  },
  "confidence": {
    "value": {
      "param": {
        "type": "string",
        "enum": [
          "5: The area chair is absolutely certain",
          "4: The area chair is confident but not absolutely certain",
          "3: The area chair is somewhat confident",
          "2: The area chair is not sure",
          "1: The area chair's evaluation is an educated guess"
        ],
        "input": "radio"
      }
    },
    "order": 3
  }
}
```

**Comment by melisabok** [comment]
Thanks for catching this typo!

@racheljsmart could you fix the documentation, please use radio instead?

It seems the code is correct: https://github.com/openreview/openreview-py/blob/master/openreview/stages/default_content.py#L342

**Comment by racheljsmart** [comment]
@melisabok I created a [change request](https://app.gitbook.com/o/ERXGmQxBo9TPGHeWheDQ/s/VorH499wd7ipUjYX5etp/~/changes/178/reference/default-forms/default-meta-review-form) for review.

**Comment by carlosmondra** [comment]
Change request has been merged.
