### ISSUE TITLE
Exported CSV doesn't have a standalone way to map from ID to email

### ISSUE THREAD

**Issue by craffel** [openreview/openreview#124]
**Is your feature request related to a problem? Please describe.**
I am working to automate the process of sending personalized reminder emails when I'm an area chair. The "export" button is helpful for this because it gives you a CSV with a column that lists the openreview usernames (e.g. ~Colin_Raffel1) of people who haven't submitted their review yet. It also has a column with all reviewers' emails. However, there is no direct way to go from a missing reviewer's ID to an email address. One could convert the username to a email-like name (e.g. "~Colin_Raffel1" -> "Colin Raffel") and hope that the corresponding email name is the same ("Colin Raffel\<craffel@gmail.com\>" -> "Colin Raffel"), but I'm finding this isn't always the case. Also, the username is presumably unique whereas the person's name presumably isn't.

**Describe the solution you'd like**
I'd like the email column to be modified so that it includes the username too.

**Describe alternatives you've considered**
I think the current best-case possibility would be to traverse the list of usernames and the list of emails and try to do some heuristic matching between the two (e.g. matching only on the last name, as determined by whitespace), but this would be error prone if two people with the same (last) name were in subsequent order in the email list. Another thing I could look into would be querying the openreview API in some way to get the email for the supplied username, but I'm not sure openreview provides this kind of information via their API and ideally the csv should be self-contained.

**Comment by melisabok** [comment]
Hi @craffel, if you are using the OpenReview API you don't need to use email addresses, using the username is enough to pass in the recipient param. 

A user can have multiple names and they are all mapped to usernames that point to the same profile. "Melisa Bok" is mapped to "~Melisa_Bok1" and "Melisa A. Bok" is mapped to "~Melisa_A._Bok1" that are pointing to the same profile that has my preferred email address that is going to be used to send the email. 

AFAIK all the reviewers listed in your console must have an OpenReview profile so you should have usernames for all of them.

Melisa

**Comment by craffel** [comment]
Hey Melisa, I was hoping to avoid using the openreview API since the CSV alone is *almost* enough - it just needs a way to associate ID with email (rather than just a list of missing IDs and a separate list of emails). I think actually if there was just one more field listing the openreview ID for *all* reviewers (not just the ones whose review is missing) in the same order as the email list it would be enough .But if using the API is the supported solution, I will do that.
