### ISSUE TITLE
In Profile Edit page, Save Changes incrementally (or move the Save Changes button to the top)

### ISSUE THREAD

**Issue by tdietterich** [openreview/openreview#125]
**Is your feature request related to a problem? Please describe.**
I made a series of changes in edit mode but then did not save them. I lost 30 minutes of work. A person's profile can be very long, so the Save Changes button at the bottom of the page is not visible. 

**Describe the solution you'd like**
The best solution would be to save each change as it is made rather than tempting the user to make a lot of changes and then save them all at one go.

**Describe alternatives you've considered**
A simpler fix would just be to put the Save Changes button at the top, or perhaps at the end of each section, so that one button is always visible. 

**Additional context**

**Comment by melisabok** [comment]
Thanks for your feedback Thomas, we will take this into account.

**Comment by carlosmondra** [comment]
Fixed here: https://github.com/openreview/openreview-web/pull/2071
