### ISSUE TITLE
Showing affiliation Dhirubhai Ambani Institute Of Information and Communication Technology with my profile name

### ISSUE THREAD

**Issue by eramonga** [openreview/openreview#126]
Dear openreview team

Request to look for additional affiliation showing in my profile as Dhirubhai Ambani Institute Of Information and Communication Technology to which I am not affiliated. Request to delete it. 

![Openreview](https://github.com/openreview/openreview/assets/149576713/f3eee5bf-dad6-4e86-888c-fe8dc84c4791)

**Comment by melisabok** [comment]
Please contact us at info@openreview.net so we can investigate why that affiliation is shown in your profile.

Melisa

**Comment by eramonga** [comment]
Thanks for the reply. To remove that extra citation, I clicked the delete
button two or three times after entering my affiliation.  You can work to
delete that issue of additional affiliations.

Regards
Amit

**Comment by carlosmondra** [comment]
If this issue has not been resolved, please send us an email to info@openreview.net
