### ISSUE TITLE
Purpose of "Edit Group" action in the Reviewer Console

### ISSUE THREAD

**Issue by habernal** [openreview/openreview#13]
**Describe the bug**
ARR ACL January, in the reviewer console at the top:

"Currently showing group in default mode" and "Edit Group"

1) What is a "group", what is a "default mode", and why is this relevant is not clear.
2) When clicking on "Edig Group", I can see perhaps all reviewers (3728 persons) and I can remove them?!

I'm afraid of clicking on anything here.

**Expected behavior**
Either explained & documented functionality or diasabled for the reviewer role.

**Screenshots**
![screenshot_2022-02-20_18-36-04](https://user-images.githubusercontent.com/11850778/154856215-2c7101b0-f91b-4d51-abd8-c77261b63038.png)
![screenshot_2022-02-20_18-36-42](https://user-images.githubusercontent.com/11850778/154856217-90bf053a-7ecd-4e04-a2e9-8c19fb2df9b2.png)

**Comment by habernal** [comment]
Oh, it seems I can even edit the general info with links to the ACL ARR reviews?!
![screenshot_2022-02-20_18-44-09](https://user-images.githubusercontent.com/11850778/154856306-1a2b049b-be02-44ea-b89e-d0a357e12e76.png)

**Comment by melisabok** [comment]
It seems your are an AC and reviewer for the January version and that's why you can have access to the edit mode. Reviewers don't have access to this UI because they are not listed as writers of the group.
