### ISSUE TITLE
OpenReview profile activation pending

### ISSUE THREAD

**Issue by MIracleyin** [openreview/openreview#130]
**Describe the bug**
I registered an account on OpenReview 12 hours ago but have not received the activation email, which prevents me from logging in. This is an issue because I wish to submit a paper to CVPR soon but cannot do so until my account is activated. I would greatly appreciate if you could manually activate my account or resend the activation email as soon as feasible. Please let me know if there is any other information I can provide to expedite this process. I look forward to being able to access my OpenReview account to submit to CVPR before the deadline.

**Expected behavior**
Activate my account

**Device information (please complete the following information):**
 - OS: macOS
 - Browser: safari

**Comment by carlosmondra** [comment]
Please send an email to info@openreview.net

And read the [guidelines](https://github.com/openreview/openreview/blob/main/CONTRIBUTING.md) before posting an issue. Thanks.

**Comment by MIracleyin** [comment]
The deadline is less than 13 hours away. The notification email went over the preset time and left me a bit overwhelmed.
I apologize for my haste, and I was sent an email to [info@openreview.net](mailto:info@openreview.net)
Thanks for your reply.
