### ISSUE TITLE
Can't see my submission of cvpr2024 after changing my name and deleting the old incorrect name

### ISSUE THREAD

**Issue by jokingww** [openreview/openreview#132]
**Describe the bug**
I can't my submission after changing my prefer name and deleting the old one. After changing my name, the ID after name is change from 2 to 1.

**To Reproduce**
1. Go to 'profile'
2. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/openreview/openreview/assets/54825315/2edb15c3-deb8-4db6-9b2c-0f127ee72980)

**Device information (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Additional context**

**Comment by racheljsmart** [comment]
The issue was resolved.
