### ISSUE TITLE
Why my profile cannot be modified？

### ISSUE THREAD

**Issue by YuyangZhao** [openreview/openreview#135]
I confront a problem after I switch to the ''Edit mode'' of my profile. 
I can open the interface of "edit profile". But after I modify the content of my profile and the system delivers message implying that I have sucessfully changed my profile, the profile have not updated. Every noticement of the system tells me that it is a successful modification,  but it doesn't work in fact. Repeat the process is useless.

**Comment by melisabok** [comment]
please send us an email at info@openreview.net with your personal info and the data you are trying to edit. Thanks.

**Comment by YuyangZhao** [comment]
> please send us an email at [info@openreview.net](mailto:info@openreview.net) with your personal info and the data you are trying to edit. Thanks.

I have sent an email to the address, wishing a helpful replyment. Thank you!
