### ISSUE TITLE
Cannot complete registration

### ISSUE THREAD

**Issue by lums658** [openreview/openreview#136]
**Describe the bug**
I am attempting to complete my registration and receive the error "Error: username ~Andrew_Lumsdaine2 is not a member of ~Andrew_Lumsdaine1" when I try to complete the registration.

**To Reproduce**
1. Go to openreview login page
2. Click on 'Sign Up'
3. Enter Full Name Andrew Lumsdaine -- page populates with various existing info, including email addresses for indiana.edu and uw.edu.
4. Click on Send Activation Link by the uw.edu address (note that I no longer have access to an indiana.edu email address)
5. Receive email with Activation Link
6. Click on Activation Link in email
7. Fill out all of the information on the page that opens
8. Click on Complete Registration
9. Error: username ~Andrew_Lumsdaine2 is not a member of ~Andrew_Lumsdaine1

**Expected behavior**
I expected to be able to complete my registration.

**Screenshots**
N/A

**Device information (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 16.6

**Additional context**
It is fairly urgent that I be able to complete my registration as I am a co-author on a recently-submitted paper.

**Comment by melisabok** [comment]
Hi Andrew,

The issue should be fixed, please try again.

**Comment by lums658** [comment]
It worked!  Thanks!

Sincerely,
Andrew Lumsdaine




On Nov 21, 2023, at 5:56 AM, Melisa Bok ***@***.***> wrote:



Hi Andrew,

The issue should be fixed, please try again.
