### ISSUE TITLE
Author names with special characters result in incorrect BibTeX key

### ISSUE THREAD

**Issue by Pseudomanifold** [openreview/openreview#138]
**Describe the bug**

If an author name has special characters, an incorrect BibTeX key is generated upon export.

**To Reproduce**
1. Go to https://openreview.net/forum?id=rIUjwxc5lj
2. Click on 'BibTeX'

**Observed behavior**

A BibTeX record with an incorrect BibTeX key:

```bibtex
@inproceedings{
t{\"o}nshoff2023where,
title={Where Did the Gap Go? Reassessing the Long-Range Graph Benchmark},
author={Jan T{\"o}nshoff and Martin Ritzert and Eran Rosenbluth and Martin Grohe},
booktitle={The Second Learning on Graphs Conference},
year={2023},
url={https://openreview.net/forum?id=rIUjwxc5lj}
}
```

The key `t{\"o}nshoff2023where` is not valid BibTeX. 

**Expected behavior**

Obtaining BibTeX that is formatted like this:

```bibtex
@inproceedings{toenshoff23awhere,
  title         = {Where Did the Gap Go? Reassessing the Long-Range Graph Benchmark},
  author        = {Jan T{\"o}nshoff and Martin Ritzert and Eran Rosenbluth and Martin Grohe},
  year          = 2023,
  booktitle     = {The Second Learning on Graphs Conference},
  url           = {https://openreview.net/forum?id=rIUjwxc5lj}
}
```

The key `toenshoff2023where` **is** valid BibTeX. 

**Device information (please complete the following information):**
 - OS: Linux (probably irrelevant)
 - Browser: Chrome and Firefox
 - Version: Lastest version (irrelevant)

**Additional context**

This could potentially be addressed by using something like the `unidecode` package:

```Python
>>> from unidecode import unidecode
>>> unidecode("tönshoff")
'tonshoff'
```

(Technically, "ö" can also be written as "oe" in Geman, but I believe that addressing this in an internationally-consistent way is probably a lot harder.)

**Comment by melisabok** [comment]
The function that creates the bibtex entry is this one: https://github.com/openreview/openreview-py/blob/master/openreview/tools.py#L421 and we are using `utf8tolatex` to format the author names. 

@celestemartinez can you take a look at this one?

**Comment by Pseudomanifold** [comment]
Dear all,

This issue still persists. My understanding is that the problem is that `utf8tolatex` incorrectly escapes characters. I would suggest a fix like this (to apply to the [`generate_bibtex`](https://github.com/openreview/openreview-py/blob/ee872f3caff090ebd0efc48c07ff51c8ea5bf95b/openreview/tools.py#L551) function):

```patch
- utf8tolatex(first_author_last_name + year + first_word + ','),
+ unicodedata.normalize(first_author_last_name + year + first_word + ',').encode("ascii", "ignore").decode("ascii"),
```

A quick demo script shows that this solves this particular problem:

```python

import unicodedata


name = "Tönshoff"
name = (
    unicodedata.normalize("NFKD", name)
    .encode("ascii", "ignore")
    .decode("ascii")
)
print(name)
```

The output of this script is `Tonshoff`.

**Comment by Pseudomanifold** [comment]
Wonderful, thanks so much!

**Comment by melisabok** [comment]
@celestemartinez can you please try to reproduce this error and try the suggested fix?
