### ISSUE TITLE
ARR ACL Reviewer Console missing rating, review, area chair

### ISSUE THREAD

**Issue by habernal** [openreview/openreview#14]
**Describe the bug**
Rating, Review, and Area Chair are missing in the ACL ARR Reviewer Console overview (see screenshot)

ACL ARR January 2022

**Screenshots**
![s_2022-02-20_19-37-48](https://user-images.githubusercontent.com/11850778/154858488-31b835de-5a89-4cea-b4fd-30b70a88df1e.png)

**Comment by melisabok** [comment]
These fields "rating" and "review" are not requested in ARR review forms. Please contact the ARR organizers, they should be able to show any other fields of the review.
