### ISSUE TITLE
Failed to register new user

### ISSUE THREAD

**Issue by caydenwei** [openreview/openreview#144]
**Describe the bug**
When register, it shows
Error: The OpenReview API is currently unavailable, please wait and try again later

**To Reproduce**
1. Fill Full Name, Emails, Linkedin URL, Eductions part
2. Click on 'Register for OpenReview'

**Screenshots**
<img width="680" alt="image" src="https://github.com/openreview/openreview/assets/21691467/def0693f-fbc9-47bf-9d3e-90b76cf13aed">

**Device information (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Comment by melisabok** [comment]
Are you still getting this error?

**Comment by caydenwei** [comment]
> Are you still getting this error?

Thank you for your reply, my issue has been resolved. It seems the problem was due to my VPN being on during registration. After turning off the VPN and switching to the Safari browser, the issue was resolved.
