### ISSUE TITLE
Errta in the example of API V2 JSON for Default Review Form

### ISSUE THREAD

**Issue by NoSyu** [openreview/openreview#145]
**Describe the bug**

In the document, the JSON example has a errata.

**To Reproduce**
1. Go to https://docs.openreview.net/reference/default-forms/default-review-form
2. On ``API V2 JSON`` section, line 3 ``"value": `` => ``"value": {``

**Expected behavior**

No JSON parsing error when we copy and paste the example

**Screenshots**
![cap_1703323531](https://github.com/openreview/openreview/assets/2724705/08e176a8-ac67-4239-acb8-615cc541b1fd)

**Device information (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 120.0.1

**Additional context**

**Comment by melisabok** [comment]
Documentation has been fixed. 

I will keep it open so @racheljsmart can review and update all the default forms.

**Comment by NoSyu** [comment]
Thank you for updating the document.

I found another bug in the document. We need to wrap up the values' values with quotation marks.

When I create a select question following the document, I encounter an error message upon submitting a review.

``XXX value must be equal to one of the allowed values: 5, 4, 3, 2, 1``

![Allowed_values](https://github.com/openreview/openreview/assets/2724705/ac3dc6d7-9d55-4827-8e43-b8248e0f6c1c)

This error occurs because there are no quotation marks around the values' values in the document.

https://docs.openreview.net/reference/default-forms/default-review-form

The JSON item that produces the error status is as follows:

```
"appropriateness": {
        "value": {
            "param": {
                "type": "string",
                "enum": [
                    {
                        "value": 5,
                        "description": "5: Certainly"
                    },
                    {
                        "value": 4,
                        "description": "4: Probably"
                    },
                    {
                        "value": 3,
                        "description": "3: Unsure"
                    },
                    {
                        "value": 2,
                        "description": "2: Probably not"
                    },
                    {
                        "value": 1,
                        "description": "1: Certainly not"
                    }
                ],
                "input": "select"
            }
        },
        "order": 2,
        "description": "Does this paper fit in the workshop? Both empirical and theoretical results are welcome."
    },
```

To fix this problem, I need to wrap it up with quotation marks as follows:

```
"appropriateness": {
        "value": {
            "param": {
                "type": "string",
                "enum": [
                    {
                        "value": "5",
                        "description": "5: Certainly"
                    },
                    {
                        "value": "4",
                        "description": "4: Probably"
                    },
                    {
                        "value": "3",
                        "description": "3: Unsure"
                    },
                    {
                        "value": "2",
                        "description": "2: Probably not"
                    },
                    {
                        "value": "1",
                        "description": "1: Certainly not"
                    }
                ],
                "input": "select"
            }
        },
        "order": 2,
        "description": "Does this paper fit in the workshop? Both empirical and theoretical results are welcome."
    },
```

Please check this error and revise the document.

Thanks!

**Comment by melisabok** [comment]
I updated the documentation to fix that issue too, the type should be integer so values don't need to be wrapped with double quotes.

**Comment by NoSyu** [comment]
> I updated the documentation to fix that issue too, the type should be integer so values don't need to be wrapped with double quotes.

Yes, that's what I know, but unfortunately, there is a bug in the submission. So I suggest updating the document :)

Thank you for your quick reply!
