### ISSUE TITLE
Withdrawl issue  Submission 3215 ICLR 2023

### ISSUE THREAD

**Issue by NaveenKumar-1311** [openreview/openreview#148]
**Describe the bug**

We have withdrawn our  Submission 3215 in ICLR 2023 and we want to delete the paper and unable to do it.  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device information (please complete the following information):**
 - OS: [e.g. iOS, Windows 10]

**Additional context**

**Comment by melisabok** [comment]
This is not an issue, ICLR withdrawn submissions remain public, I suggest you contact the organizers to ask for more details.
