### ISSUE TITLE
ACL ARR reviewer names are revealed to other reviewers

### ISSUE THREAD

**Issue by habernal** [openreview/openreview#15]
**Describe the bug**
I'm not sure if this is intentional or not, but as as reviewer, I can see other reviewers' names, e.g.:

```
ACL ARR 2022 January PaperXXX Reviewer XXX FirstName SecondName (privately revealed to you)
```

**Expected behavior**
I believe reviewers should stay anonymous among themselves. I don't see any reason for doing otherwise. Maybe double-check with ARR editors.

**Comment by melisabok** [comment]
It seems the ARR organizers specified this, please check with the ARR organizers.
