### ISSUE TITLE
Cannot receive the activation email for our company email: @chinamobile.com

### ISSUE THREAD

**Issue by kernelLZ** [openreview/openreview#151]
**Describe the bug**
Cannot receive the activation email for our company email: xx@chinamobile.com

**To Reproduce**
1. Go to '[...](https://openreview.net/login)'
2. Click on 'Login into Openreview
4. See error：Cannot receive the activation email for our company email: lizhenit@chinamobile.com; taotao@chinamobile.com,chenzhuoit@chinamobile.com;wangjibin@chinamobile.com

**Expected behavior**
We hope to receive the activation email as soon as possilbile

**Screenshots**
![image](https://github.com/openreview/openreview/assets/26424148/b8d0bcce-87f5-4e50-96ab-43b374658180)

**Device information (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Edge]

**Additional context**

**Comment by carlosmondra** [comment]
Please read the [guidelines](https://github.com/openreview/openreview/blob/main/CONTRIBUTING.md#identify-where-to-report) before submitting an issue. This issue in particular needs to be reported to info@openreview.net. Thank you.
