### ISSUE TITLE
Cannot Access ECCV 2020 Conference Author Console

### ISSUE THREAD

**Issue by chimax** [openreview/openreview#153]
**Describe the bug**
After logging in to the account with which I submitted a manuscript as an author to ECCV 2020 Conference,
when accessing this page:
https://openreview.net/group?id=thecvf.com/ECCV/2020/Conference/Authors
it fails to load up, and an error message displays:
"Error: invitation must be a prefix regex. If validation passes, any remaining regex characters will be escaped."

**To Reproduce**
1. Log in to an author account of ECCV 2020 Conference
2. Go to the main page of OpenReview (https://openreview.net/)
3. Under "All Venues", click on "ECCV"
4. Click on "ECCV 2020"
5. Click on "[thecvf.com/ECCV/2020/Conference](https://openreview.net/group?id=thecvf.com/ECCV/2020/Conference)"
6. Click on "Author Console"
7. See error

**Expected behavior**
Expected to load up a list of submitted manuscripts to this conference.

**Screenshots**
N/A

**Device information (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 120.0.6099.225 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by zbialecki** [comment]
Thank you for alerting us to this issue. The ECCV 2020 Conference Author Console has been updated and you should be able to access your submissions again.

**Comment by chimax** [comment]
> Thank you for alerting us to this issue. The ECCV 2020 Conference Author Console has been updated and you should be able to access your submissions again.

Thank you for solving this issue and your timely response!
