### ISSUE TITLE
Cannot exclude a paper authored under non-preferred name from the reviewer expertise

### ISSUE THREAD

**Issue by dantrag** [openreview/openreview#154]
**Describe the bug**
I have authored papers under two names (changed my last name a few years ago). Both are listed in my profile as
Alexander Oldlastname (~Alexander_Oldlastname1)
Alexander Newlastname (~Alexander_Newlastname1)  <-- selected as preferred (current)

I received an invite to be a reviewer, and I need to make a selection for the papers that define my expertise. A list of papers was fetched from DBLP.org, and I want to exclude a paper that was authored under 'Oldlastname'. When I press Expertise selection: Exclude, I receive the error message:

`Error: tail "~Alexander_Oldlastname1" is not member of auai.org/UAI/2024/Conference/Reviewers`

I don't know what the best solution is here, maybe just check all associated accounts instead of only preferred one?

**Comment by melisabok** [comment]
The issue should be fixed, please try again.

**Comment by dantrag** [comment]
Fixed now, thanks!

**Comment by dantrag** [comment]
Fixed now, thanks!
