### ISSUE TITLE
Can't confirm second email (profile IDs "undefined")

### ISSUE THREAD

**Issue by sjmielke** [openreview/openreview#158]
My profile (~Sabrina_J_Mielke1) has an unconfirmed email that I want to confirm (and make primary), but when trying to confirm it I see a message:

"Error: [undefined](https://openreview.net/profile?id=undefined) is already associated with another OpenReview profile, undefined. To merge this profile with your account, please click here to submit a profile merge request: [Merge Profiles](https://openreview.net/profile/edit#)."

Unsurprisingly, the merge box's submit button does not work whe nthe box says "undefined,undefined".

**Device information (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 122

**Comment by melisabok** [comment]
Hi Sabrina, 

It seems both email accounts were confirmed but something was wrong with the data, I think I fixed it. 

Could you please try logging in using both email addresses and let me know if it works in both cases?

Thanks,

Melisa

**Comment by sjmielke** [comment]
Hi Melisa,I can confirm it works with both addresses now. Thanks!!Best regards,SabrinaOn Feb 12, 2024, at 9:48 AM, Melisa Bok ***@***.***> wrote:﻿
Hi Sabrina,
It seems both email accounts were confirmed but something was wrong with the data, I think I fixed it.
Could you please try logging in using both email addresses and let me know if it works in both cases?
Thanks,
Melisa
