### ISSUE TITLE
OpenReview profile activation pending

### ISSUE THREAD

**Issue by masaikk** [openreview/openreview#159]
I registered an account on OpenReview a few hours ago but have not received the activation email, which prevents me from logging in. This is an issue because I wish to submit a paper to ACL soon but cannot do so until my account is activated. I would greatly appreciate if you could manually activate my account or resend the activation email as soon as feasible. Please let me know if there is any other information I can provide to expedite this process. I look forward to being able to access my OpenReview account to submit to ACL before the deadline.

**Comment by carlosmondra** [comment]
Please read the [guidelines](https://github.com/openreview/openreview/blob/main/CONTRIBUTING.md) before submitting an issue.

> If you have a problem with your account that requires you to share personal information such as your email or name, please contact us at [info@openreview.net](mailto:info@openreview.net).

I see that you already sent an email to info@openreview.net. I will close this issue.
