### ISSUE TITLE
ACL ARR AC Console: Meta review status not shown

### ISSUE THREAD

**Issue by habernal** [openreview/openreview#16]
**Describe the bug**
After filling out the meta review, no status has changed in the Area Console. Column "Meta Review Status" displays "Submit" for all papers regardless of whether the meta review has been written or not.

**Screenshots**
![s_2022-02-20_20-01-26](https://user-images.githubusercontent.com/11850778/154859677-e506ef5c-88ed-4ad6-8cb6-73b1747040a3.png)

**Comment by melisabok** [comment]
Fixed.

Please report these issues to the ARR organizers, thanks!
