### ISSUE TITLE
Not able to see the review task which was assigned to me.

### ISSUE THREAD

**Issue by robot-Yang** [openreview/openreview#161]
<img width="793" alt="Screenshot 2024-02-22 at 18 19 06" src="https://github.com/openreview/openreview/assets/9564889/81caf9ef-34de-4d78-99af-268e77ce5a3e">  

I was assigned to review a paper a few days ago, but when I click the link, it shows this error.

Any clue? Thanks.

**Comment by carlosmondra** [comment]
These issues require to share personal information. Please follow the [guidelines](https://github.com/openreview/openreview/blob/main/CONTRIBUTING.md). Thanks!
