### ISSUE TITLE
Add @ispras.ru email domain addresses as an "approved" institution. I need to submit an article before March 18th

### ISSUE THREAD

**Issue by oksidgy** [openreview/openreview#164]
Please add the **@ispras.ru** email domain (to the list of verified institutes). 

I need to submit the article before March 18th!

> If you sign up with a public domain or an email domain that is not included in our institution list you will see a warning ... signing up with a public domain may spend up to 2 weeks in moderation.

Institute website: https://www.ispras.ru/en/

![image](https://github.com/openreview/openreview/assets/18547852/b6f4d045-834c-471c-b054-c2bbfc797e2d)

<img width="630" alt="image" src="https://github.com/openreview/openreview/assets/18547852/fd4c08d9-9088-46c0-9536-3df2982da3c8">

**Comment by oksidgy** [comment]
![photo_2024-03-15_13-29-23](https://github.com/openreview/openreview/assets/18547852/ea7b03f1-9dc4-4b67-9458-6c1f6a7244cd)

**Comment by oksidgy** [comment]
<img width="630" alt="image" src="https://github.com/openreview/openreview/assets/18547852/3a504d89-4588-4b21-a2f2-a039033d3eea">

**Comment by racheljsmart** [comment]
The @ispras.ru domain has been added to our institution list.
