### ISSUE TITLE
Cannot register an account

### ISSUE THREAD

**Issue by Baiqi-Li** [openreview/openreview#166]
A while ago, I used [DELETED] to register a new account, but it hasn't been activated yet. I received the message: "Your OpenReview profile has been successfully created. Please allow up to 2 weeks before the profile is activated." However, I urgently need to submit a paper now. I would greatly appreciate your assistance.

**Comment by daixiangzi** [comment]
+1

**Comment by racheljsmart** [comment]
Please email us at info@openreview.net for issues regarding profile signup. We want to avoid sharing personal information like email addresses in the github issues.

**Comment by Baiqi-Li** [comment]
Thank you very much for your help. @racheljsmart
