### ISSUE TITLE
Additional or more general fields: Advisors, Relations & Conflicts

### ISSUE THREAD

**Issue by esalesky** [openreview/openreview#167]
It would be helpful to have additional (or more general) fields in the relationships and conflicts category.  
Currently, for advisor/advisee relationships, there are only PhD and Postdoc. It could be good to also include Masters and Undergraduate Advisors, or perhaps more generally Advisor (other) in order to not enumerate all possible categories, and also broadly cover other mentor/mentee relationships which may not have resulted in coauthorship.

**Comment by melisabok** [comment]
Any option that is not available in the dropdown list can be added just typing it in.

**Comment by esalesky** [comment]
Thank you! I did not realize that. It could be worth adding to the instructions above the section. Closing!

**Comment by melisabok** [comment]
The placeholder says "choose or type a relation":

<img width="230" alt="Screen Shot 2024-04-01 at 11 50 02 AM" src="https://github.com/openreview/openreview/assets/545506/e3a209db-5179-48e9-bbc2-f583dfb80b50">

We will try to make it more clear.

**Comment by racheljsmart** [comment]
Perhaps we can add an the "i" icon next to Relation that links to a page in the documentation, like we do for the DBLP URL. I could add a line in this page for the Advisors and Other Relations section https://docs.openreview.net/getting-started/creating-an-openreview-profile/entering-institutional-data

**Comment by Xovee** [comment]
It is true that the instruction for typing should be more apparent. I didn't realize I can manually type relations there, at all.

Or maybe, I suggest to at least include the Master Advisor/Advisee options as two of the default options, helps a lot for many of the users.
