### ISSUE TITLE
Unable to submit camera-ready revision with "Invalid group id" error

### ISSUE THREAD

**Issue by Mukosame** [openreview/openreview#168]
**Describe the bug**
I am hosting a venue with id thecvf.com/CVPR/2024/Workshop/CV4MR . I have enabled the revision stage following the guidance here(https://docs.openreview.net/how-to-guides/workflow/how-to-enable-camera-ready-revision-upload-for-accepted-papers). The authors can see the "revision" button in the paper's page, but when they try to upload the revised version and submit, the following error happens: 
```
Invalid group id thecvf.com/CVPR/2024/Workshop/CV4MR/Submission1/Program Chairs
```
So far, no authors can submit the revision.

**To Reproduce**
1. Go to 'https://openreview.net/group?id=thecvf.com/CVPR/2024/Workshop/CV4MR/Authors#your-submissions'
2. Click on 'edit-revision'
3. Scroll down to the bottom and click 'submit' button
4. See error "Invalid group id thecvf.com/CVPR/2024/Workshop/CV4MR/SubmissionN/Program Chairs"

**Expected behavior**

**Screenshots**
<img width="1011" alt="Screenshot 2024-04-04 at 5 35 56 PM" src="https://github.com/openreview/openreview/assets/6279720/d741b291-ce2e-4785-a6d6-923fa2a9486d">

**Device information (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version 123.0.6312.105 (Official Build) (arm64)

**Comment by melisabok** [comment]
It is missing an _ in the group id "Program Chairs"

**Comment by Mukosame** [comment]
Thanks! Removing that group id solves the problem
