### ISSUE TITLE
Self-host OpenReview

### ISSUE THREAD

**Issue by timbmg** [openreview/openreview#169]
As far as I understand, the OpenReview front end is fully open-source. Is there any plan to make the backend publicly available, such that OR could be fully self-hosted? 

On https://openreview.net/about it says:
> Many other parts of the OpenReview platform are also open source, and are available in the [OpenReview organization on GitHub.](https://github.com/openreview) Some further releases are pending a professional security review of the codebase.

Specifically, I believe it would be great to use OpenReview for "internal reviews" as well. For this purpose, I do not want to create a venue on the platform (and I am not sure if it would be granted). However, a self-hosted solution could make junior folks more familiar with the platform, professionalize internal reviews, and facilitate data collection.

**Comment by carlosmondra** [comment]
Hi @timbmg,

As it is stated in the [about page](https://openreview.net/about), we are undergoing a professional security review of the codebase. On top of that, we are working on a license that will allow us to open source the code. The license should allow you to host OpenRevew internally, but we are still working on the details.

**Comment by timbmg** [comment]
Thanks for the quick reply, @carlosmondra! That sounds very promising 🙂 Is there a timeline? How long do you think the codebase review will take?

**Comment by carlosmondra** [comment]
We don't have timeline for this. I estimate it's going to take another 3 months, but it might be longer. We want this to happen soon though.

**Comment by timbmg** [comment]
Hi @carlosmondra, just checking in to see if there are any updates on this. Thanks!

**Comment by timbmg** [comment]
Just pinging this again; is there an update or new timeline?:)

**Comment by carlosmondra** [comment]
Hi @timbmg, 

Thanks for bringing this to my attention again. The security audit took longer than we thought. There are many things that we want to take care of, since OpenReview has become more and more popular and the amount of attacks has increased as well. Therefore, we changed our mind and decided not to opensource the code, at least for now. We may revisit this in the future.
Apologies for this, but we believe that this is what is best for us and our users.

**Comment by timbmg** [comment]
Thanks for the update, @carlosmondra. I understand the need to prioritize security. While I am a bit disappointed that the code won't be open-sourced now, I appreciate your transparency and the hard work on OR. I look forward to future updates and hope the open-sourcing can be revisited.
