### ISSUE TITLE
Inquiry Regarding Account Activation Delay Despite Institutional Email Use

### ISSUE THREAD

**Issue by NeonJing** [openreview/openreview#170]
I recently signed up for an account on OpenReview and provided my academic email address during the registration process. However, I noticed that my profile still indicates that activation could take up to two weeks, mentioning the absence of any institutional affiliation.

I have indeed used my institutional email and would appreciate your assistance in clarifying this matter. Could you kindly look into this and confirm whether there is any additional information required on my end to expedite the activation process?

this is my school email: [DELETED]

Thank you for your time and assistance.

**Comment by carlosmondra** [comment]
I see that your profile has already been activated. I deleted your email from the issue because we don't want to show personal information. Please follow the guidelines when posting issues. 

Let us know if you are still facing any issues.
