### ISSUE TITLE
Inquiry Regarding Registration Confirmation Email Not Received

### ISSUE THREAD

**Issue by ppx-hub** [openreview/openreview#171]
Dear OpenReview Support Team,

	I hope this message finds you well. I recently attempted to register an account on OpenReview, but I have not yet received the confirmation email necessary to complete my registration. I have checked my email inbox and spam folder, but the confirmation email is nowhere to be found.

	Could you please assist me by checking on the status of my registration and resend the confirmation email if necessary? For your reference, my registration email address is [[hexiang21@mails.ucas.ac.cn](mailto:hexiang21@mails.ucas.ac.cn)].

	Thank you for your attention to this matter. I look forward to your prompt response.

	Best regards,

**Comment by melisabok** [comment]
Please send us an email at info@openreview.net from your email account so we can share the confirmation link.
