### ISSUE TITLE
Names in openreview can't be displayed on google shcolar!

### ISSUE THREAD

**Issue by Baiqi-Li** [openreview/openreview#172]
**Describe the bug**
My co-authors and I submitted an article via openreview and I am the first author, but unfortunately, when I check google scholar, my name is not shown under the corresponding paper in the google scholar search page. I suspect that it may be related to the fact that my openreview name contains a "-" symbol. What should I do? I am very much looking forward to your help!

**Reproduced**
Steps to reproduce the behavior
1. Go to "Google Scholar
2. Search for "paper name".
3. Error "I can't see my name under the title of the paper."

**Expected behavior**
Please help me to fix this bug or change the username.

**Comment by Baiqi-Li** [comment]
The name I use in my openreview contains the "-" symbol like my current github name, which I realize is probably not canonical. Please let me know if this bug is due to my naming or something else. What should I do?

**Comment by Baiqi-Li** [comment]
Thank you very much and look forward to your help!

**Comment by melisabok** [comment]
I replied to your email, please provide a paper title that doesn't appear in Google Scholar so we can investigate.

**Comment by Baiqi-Li** [comment]
Thank you very much for your kind help, here are the relevant screenshots
on my openreview and google scholar profile:

[image: image.png][image: image.png]



*If possible, I would like to change my name from "Baiqi-Li" to "Baiqi
Li".Thanks again for your help!*

Melisa Bok ***@***.***> 于2024年4月15日周一 22:00写道：

**Comment by melisabok** [comment]
Sorry I can not see the pictures.

**Comment by Baiqi-Li** [comment]
Here is the title of my paper:


*"GenAI-Bench: A Holistic Benchmark for Compositional Text-to-Visual
Generation"*

*If possible, I would like to change my name from "Baiqi-Li" to "Baiqi
Li".Thanks again for your help!*

Melisa Bok ***@***.***> 于2024年4月15日周一 22:18写道：

**Comment by melisabok** [comment]
Thanks, I can confirm the name doesn't appear in Google Scholar. Let me forward this to the Google Scholar and get back to you. 

I prefer to wait until we figure out the issue before changing your name. 

<img width="965" alt="Screen Shot 2024-04-15 at 10 30 29 AM" src="https://github.com/openreview/openreview/assets/545506/62842be4-8eb5-4e53-b14c-a6b92fe5e88f">

**Comment by Baiqi-Li** [comment]
Thank you for your help.

I have a few concerns:

1. I plan to add the scholar link of this paper to my resume soon for
internships and job opportunities, so I'm looking forward to resolving this
soon.
2. I realize that my previous name is not up to standard, so I would prefer
to use a more standard new name.

I apologize for any trouble I may have caused you!

Melisa Bok ***@***.***> 于2024年4月15日周一 22:32写道：

**Comment by melisabok** [comment]
Ok, you can add a new name to your profile and request the deletion of the other name. 

Anyway I'm not sure how often Google Scholar will index your paper.

You can use your openreview profile url on your resume :)

**Comment by Baiqi-Li** [comment]
Nice! Thank you for your advice.

Melisa Bok ***@***.***> 于2024年4月15日周一 22:49写道：

**Comment by melisabok** [comment]
I approved your name deletion and now your submission has the name changed: https://openreview.net/forum?id=hJm7qnW3ym

I contacted Google Scholar and they are going to try to recrawl this paper as soon as they can.
