### ISSUE TITLE
Eror 404

### ISSUE THREAD

**Issue by MartCZ8** [openreview/openreview#175]
**Describe the bug**
When clicking on the Reviewers Paper Assignment in the timeline, the error 404 message appears: "there is currently no assignment configuration ready for use. Please go to your venue request form and use the Paper Matching Setup to compute conflicts and/or affinity scores." But, there is no longer the paper matching setup available when I go back 
<img width="1189" alt="Screenshot 2024-04-26 at 22 29 11" src="https://github.com/openreview/openreview/assets/168231979/5bf28efd-c6f1-4d8b-98e3-e609d7cce53e">
to Full venue configuration.

**Comment by melisabok** [comment]
Make sure the submission deadline is in the past.

**Comment by MartCZ8** [comment]
I see, thank you. I wanted to try everything before we start with the submission period so I know how things work. If I get it correctly, will the Paper Matching Setup appear again?
Thanks for your time!
