### ISSUE TITLE
Profile edits were not saved!

### ISSUE THREAD

**Issue by kalo-ai** [openreview/openreview#177]
**Is your feature request related to a problem? Please describe.**
I was editing my profile. When I finished my edits, I clicked "View Profile". What happened is that all my changes were lost (what a waste of time...). Then I realized that I had to go all the way down the page and click save.... 

**Describe the solution you'd like**
The save button is in the wrong place -- the edits were much higher on the top of the page (co-authors). There should be buttons for saving the profile next to the edits, or at every section, including on the top. When you click "View profile", the page should ask if the changes should be saved. *Or even better, the changes should be saved immediately without clicking anything.* 

**Describe alternatives you've considered**

**Additional context**

**Comment by carlosmondra** [comment]
This has been fixed here: https://github.com/openreview/openreview-web/pull/2071
