### ISSUE TITLE
Paper review page ("forum") should display paper number

### ISSUE THREAD

**Issue by habernal** [openreview/openreview#18]
**Is your feature request related to a problem? Please describe.**
While the overview of papers (either for reviewer or for area chair, e.g. https://openreview.net/group?id=aclweb.org/ACL/ARR/2022/January/Area_Chairs) shows also the paper number (column "#"), this is not shown anywhere in the review page (e.g., https://openreview.net/forum?id=xxxxxxxx ). These numbers are helpful for area chairs to manage and navigate their papers faster.

**Describe the solution you'd like**
Show the paper # somewhere on the review page (top?).

**Describe alternatives you've considered**
I don't see any.

**Comment by zbialecki** [comment]
Thanks for the feedback. We are working on some enhancements to the forum page and can definitely incorporate this.
