### ISSUE TITLE
OpenReview profile activation pending

### ISSUE THREAD

**Issue by RabbitDF** [openreview/openreview#180]
I have registered an openreview account and filled in my profile information, but due to my preferred email being filled in with a personal email, it shows "Your profile does not contain any institution email and it can take up to 2 weeks for your profile to be activated.".
I need to submit to NeuralIPS 2024 with a abstract submission deadline of May 15, 2024 01:00 PM PDT, so it is urgent to have an openreview account.

Name: Fan Zhang
Profile username: ~Fan_Zhang47
Email 1: 18309234071@163.com
Email 2: fan02.zhang@samsung.com

I've sent an email to info@openreview.net, but since the deadline is so close,please review and activate my account as soon as possible! 
Please let me know if there is any other information I can provide to expedite this process.
Thank you very much!

**Comment by carlosmondra** [comment]
Thanks for getting in touch with us. I will close this issue because it contains personal information and several issues are similar to this one. I see that you already sent an email to info@openreview.net.
Please follow the [guidelines](https://github.com/openreview/openreview/blob/main/CONTRIBUTING.md) for future issues.

**Comment by RabbitDF** [comment]
> Thanks for getting in touch with us. I will close this issue because it contains personal information and several issues are similar to this one. I see that you already sent an email to [info@openreview.net](mailto:info@openreview.net). Please follow the [guidelines](https://github.com/openreview/openreview/blob/main/CONTRIBUTING.md) for future issues.

Thanks for your quick help!
