### ISSUE TITLE
[Urgent] Error: username ~FirstName_LastName2 is not a member of ~FirstName_LastName1

### ISSUE THREAD

**Issue by ngxbac** [openreview/openreview#181]
**Describe the bug**
My co-author and I are trying to create and activate an account. However, we got the same issue as in this [bug report](https://github.com/openreview/openreview/issues/88). 
In particular, the error is: "Error: username ~Pawan_Sinha2 is not a member of ~Pawan_Sinha1". 
Since the deadline is approaching, would you please help us fix it?

Best regards,

**Comment by melisabok** [comment]
it should be fixed, could you please try again?
