### ISSUE TITLE
Nomination Text Entry Error

### ISSUE THREAD

**Issue by aahmedqau** [openreview/openreview#183]
Reviewer Nomination value must match pattern "~.*|([a-z0-9_\-\.]{1,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,},){0,}([a-z0-9_\-\.]{1,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,})"

the form is not submitting; I have entered the nomination with the author's name, but this error still exists; please do something.

**Comment by melisabok** [comment]
Can you share the venue id or send us an email at info@openreview.net with more information?

**Comment by aahmedqau** [comment]
venue is NeurIPS
https://openreview.net/group?id=NeurIPS.cc/2024/Datasets_and_Benchmarks_Track#tab-recent-activity
NeurIPS 2024 Datasets and Benchmarks Track Submission

**Comment by melisabok** [comment]
Please contact the venue organizers and share the issue with them.
