### ISSUE TITLE
profile activation pending but DDL is approaching

### ISSUE THREAD

**Issue by kyrielw24** [openreview/openreview#184]
Yesterday, I registered an account on OpenReview but did not receive an activation email and therefore could not log in. This is a problem because I would like to submit a paper to NeurIPS 2024 Track Datasets and Benchmarks as soon as possible, but cannot do so until my account is activated. I would appreciate it if you could manually activate my account or resend the activation email as soon as possible. Please let me know if there is any other information I can provide to speed up the process. I look forward to accessing my OpenReview account and submitting my paper before the deadline.
My email is liuwei030224@gmail.com.
Your help is greatly appreciated!

**Comment by kyrielw24** [comment]
DDL is approaching!

**Comment by melisabok** [comment]
profile is active now.
