### ISSUE TITLE
Getting spam "conference" invites which link to website with virus

### ISSUE THREAD

**Issue by amyxie361** [openreview/openreview#185]
**Describe the bug**
I got an invite to be reviewer of WiNLP. When checking the "conference" webpage, it hacked into chrome allowed notification from "brownsisteroftime", and send spam alerts. And it seems not a legit conference from the home-page

**Expected behavior**
Is there some procedures from open reivew to prevent sharing our contact information with any "conference" organizer as they want?

**Device information (please complete the following information):**
 - OS: [Mac-iOS]
 - Browser [chrome]

**Additional context**
Would like to know more about the machinism of orgnizers getting reviewer's contact, and would like to help protect our privacy if there's anything I can help with.

**Comment by melisabok** [comment]
Thanks for reporting this. We will check with the EMNLP organizers if this is a valid workshop.

**Comment by santoshTYSS** [comment]
Hi, I am one of co-chairs of workshop and its a valid workshop posted under EMNLP - https://2024.emnlp.org/program/workshops/ as well. We are not really sure what's causing this and are working on it currently to fix the website.

**Comment by carlosmondra** [comment]
@amyxie361 was this fixed?
