### ISSUE TITLE
About account activation

### ISSUE THREAD

**Issue by Bingyang0410** [openreview/openreview#188]
have registered an openreview account and filled in my profile information, but due to my preferred email being filled in with a personal email, it shows "Your profile does not contain any institution email and it can take up to 2 weeks for your profile to be activated.".
I need to submit to NeuralIPS 2024 with a abstract submission deadline of June 5th, 2024 01:00 PM PDT, so it is urgent to have an openreview account.

The email is [gloriags@163.com](mailto:gloriags@163.com)

**Comment by carlosmondra** [comment]
Please follow the [guidelines](https://github.com/openreview/openreview/blob/main/CONTRIBUTING.md)
