### ISSUE TITLE
Error in requesting for resetting password to a user account of Gmail

### ISSUE THREAD

**Issue by ffzhou** [openreview/openreview#190]
**Describe the bug**

I want to reset the password of my OpenReview account (FengfengZhou@gmail.com)

But I get no response emails.

Could you please help me check this issu?

Best,

**To Reproduce**
1. Go to 'Login'
2. Click on '[Forgot your password?](https://openreview.net/reset)'
3. Scroll down to 'Input an account with the Gmail email address'
4. See error: no response could be received in my gmail mailbox.

**Expected behavior**

**Screenshots**

**Device information (please complete the following information):**
 - OS: [e.g. iOS, Windows 10]

**Additional context**

**Comment by melisabok** [comment]
there is no profile associated with fengfengzhou@gmail.com, you need to sign up first.

**Comment by ffzhou** [comment]
Thanks!

I'll sign up my email.
