### ISSUE TITLE
Account Activation

### ISSUE THREAD

**Issue by isha01agr** [openreview/openreview#194]
Hi
I have created a request to create a user account to publish my research paper for Neurips - https://neurips.cc/Conferences/2024/CallforHighSchoolProjects.
When i create an account on open review, I am getting this message - Your open review profile has been successfully created. Please allow upto 2 weeks before the profile is activated.

The Neurips project submission is due on June 27th. Can you please activate my profile so that I can complete the project submission in time? I have registered with the following email IDs-
isha.cmu@gmail.com
surbhi_agrawal@bcbstx.com

Thanks for all your help.

Regards
Isha Agrawal

**Comment by melisabok** [comment]
Your profile is active now.
