### ISSUE TITLE
getting every notification twice

### ISSUE THREAD

**Issue by PaulLerner** [openreview/openreview#199]
**Describe the bug**
Since early June, I'm getting every notification twice

**Screenshots**
notification duplicates

![Capture d’écran du 2024-07-04 14-11-53](https://github.com/openreview/openreview/assets/25532159/3d657a2b-aec2-4364-b8a4-4c443741afb7)

before June it was fine

![Capture d’écran du 2024-07-04 14-12-38](https://github.com/openreview/openreview/assets/25532159/95a9d284-76cd-4040-8952-0220ba1cf3c0)

**Device information (please complete the following information):**
 - OS: ubuntu 22
 - firefox

**Comment by melisabok** [comment]
Thanks for reporting this, @haroldrubio can you take a look?

**Comment by carlosmondra** [comment]
This was from the emailing options. It sent out emails once per assignment and they had 2 assigned papers. This is no longer an issue
