### ISSUE TITLE
can't add ACL anthology link to profile

### ISSUE THREAD

**Issue by strubell** [openreview/openreview#200]
**Describe the bug**
When I try to add my ACL profile link to my OpenReview profile, it fails and I get the following error at the top of the page:
Error: An unexpected Error ocurred: 2024-07-08-3502650 (2024-07-08-3502650)

**To Reproduce**
1. Go to profile page
2. Select edit mode
3. Paste link in ACL Anthology URL box. (Link: https://aclanthology.org/people/e/emma-strubell/)
4. Select save profile changes

**Expected behavior**
The link to be added with no error.

**Screenshots**
Can add if needed.

**Device information (please complete the following information):**
 - OS: macOS 14.4.1 (23E224)
 - Browser: Chrome
 - Version: 125.0.6422.141

**Additional context**
I've tried using incognito mode, and the Safari browser. Someone else was able to add my link to their profile successfully. And I've tried doing this over many months, consistently getting the same error.

**Comment by melisabok** [comment]
Checking the logs, something must be wrong with the data @akshatchhabra  can you take a look?

![Screen Shot 2024-07-08 at 5 18 37 PM](https://github.com/openreview/openreview/assets/545506/43182728-1d12-45de-9a8e-a32887a418cc)

**Comment by akshatchhabra** [comment]
Sure, I am looking into it

**Comment by akshatchhabra** [comment]
Hi Emma, it should be fixed now. We've also added the ACL link to your profile. Please let us know if you are still facing issues.

**Comment by strubell** [comment]
Fantastic, thank you so much!
