### ISSUE TITLE
Old email address was displayed when sending system messages

### ISSUE THREAD

**Issue by yumeng5** [openreview/openreview#202]
**Is your feature request related to a problem? Please describe.**
When I sent system messages (e.g., review invitations), the email address displayed at the end of the message was not my preferred email set in my OpenReview profile. The first screenshot shows that the email address displayed was my illinois edu account (which is about to expire soon):

![Screenshot 2024-07-15 at 8 33 59 PM](https://github.com/user-attachments/assets/0dafc789-2781-4140-924a-1a4a9b8e3f8b)

The second screenshot shows that my preferred email address in my OpenReview profile is my virginia edu account.

![image](https://github.com/user-attachments/assets/329d596f-185a-4443-bda9-fdfb9947b26f)

**Describe the solution you'd like**
Display the preferred email address set in one's OpenReview profile in the system messages. Otherwise, the receiver of the message may try to contact an expired email account.

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by carlosmondra** [comment]
We no longer place the email in the signature. So this issue is no longer applicable.
