### ISSUE TITLE
Do not have permission to access a url of a paper, reported 403 error

### ISSUE THREAD

**Issue by 1836897243** [openreview/openreview#204]
**Describe the bug**
I received a URL in an email related to a paper where I am one of the authors. And I have added the same email address to my OpenReview profile, which has been confirmed.  However, I am unable to access the page.

**To Reproduce**
1. Open the email where the URL was received.
2. Click on the URL provided in the email.
3. Encounter the error.

**Expected behavior**
I expected that clicking on the URL would take me to the page where I can view or manage my paper submission details.

**Screenshots**
![image](https://github.com/user-attachments/assets/34fa686d-a641-4018-b9b3-a7a157195b04)

**Device information (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]

**Additional context**

**Comment by melisabok** [comment]
Please send us an email at info@openreview so we can investigate your case.
