### ISSUE TITLE
Error: The OpenReview APl is currently unavailable, please wait and try again later

### ISSUE THREAD

**Issue by yangyang-1** [openreview/openreview#206]
**Describe the bug**
When updating my submission, I cannot upload a new pdf file of my paper

**To Reproduce**
1. Go to submission page
2. Click on  “Choose PDF"
3. Upload pdf file of the paper

**Expected behavior**
I can  successfully upload pdf file and update my submission

**Screenshots**
![image](https://github.com/user-attachments/assets/603437a4-c797-4337-b70a-237d8585e512)

**Device information (please complete the following information):**
 - OS:  Windows 10
 - Browser Microsoft edge
 - Version 22

**Comment by melisabok** [comment]
The API is up and running now. Can you please check again and close the issue? Thanks.
