### ISSUE TITLE
Request to add profiles early due to approaching paper submission deadline

### ISSUE THREAD

**Issue by Bhardwaj-Rishabh** [openreview/openreview#207]
Dear OpenReview Committee,

We have a deadline for the EMNLP demo track, and many of our authors are not yet registered on OpenReview and use Gmail accounts. I would be grateful if you could guide us on how to add their profiles as soon as possible. The following are their email addresses:

jiahngkoh@gmail.com 
darwin@tensorplex.ai

The paper deadline is in 36 hours. I hope you understand, and I apologize for the inconvenience.

Best regards,

**Comment by melisabok** [comment]
Please use our support email account info@openreview.net to share personal data.

Closing this issue.
