### ISSUE TITLE
Request to activate my account or add @1utar.my email domain to the openreview educational institutions list as soon as possible

### ISSUE THREAD

**Issue by Erikdai** [openreview/openreview#208]
**I am a student at Universiti Tunku Abdul Rahman Malaysia, and I need to submit papers at EMNLP and AAAI conferences. However, when I registered for openreview, I found that my student email indicated that @1utar.my was not in the list of openreview educational institutions, so I registered using private gmail.  As the submission date is approaching, I hope to activate the openreview account I registered with gmai as soon as possible, or add @1utar.my to the list of educational institutions, so that I can register the openreview account quickly.**

1. Activate the following email account as soon as possible: daicxx1226@gmail.com
2. Add the @1utar.my email domain to the openreview list of educational institutions so that I can quickly re-register my account without waiting two weeks for activation.

Best regards,

**Comment by melisabok** [comment]
Profile is active now.
