### ISSUE TITLE
please help to activate my account.

### ISSUE THREAD

**Issue by MaoFengLuo** [openreview/openreview#209]
I've had my account registered for 1 month but not been successful. As the AAAI submission due date will end on August 7th, please help urgently with this matter. Thanks a lot.
Name:
Mao_Feng_Luo1
or
Mao_Feng_Luo2

**Comment by melisabok** [comment]
Mao_Feng_Luo1 is active now, you should complete the registration for Mao_Feng_Luo2 and then merge the profiles.

**Comment by ajbanks** [comment]
Hi Melisa. Im also having a similar issue. Could you also help with my profile as well please? 

Alexander_joseph1

**Comment by MaoFengLuo** [comment]
Thank you so much.
