### ISSUE TITLE
Unable to sign up; stuck in the full name confirmation step

### ISSUE THREAD

**Issue by Konjak2e8** [openreview/openreview#211]
**Describe the bug**
I want to sign up for openreview.net. During the sign up procedure, the "Register" button on the "Confirm Full Name" popup is disabled.

**To Reproduce**
1. Go to 'Sign Up' 
![image](https://github.com/user-attachments/assets/604fad86-7c89-44eb-8694-1096e3d2136a)
2. Enter my full name and email, and click "sign up"
![image](https://github.com/user-attachments/assets/d369e3f2-dea8-4bad-820a-d6781bb7f4e4)
3. Enter password and click 'sign up'
![image](https://github.com/user-attachments/assets/5ef4f5ac-3820-4d79-a5da-cfad63443ee8)
4. Click "I confirm my name is correct"
![image](https://github.com/user-attachments/assets/addd227e-a75c-4516-8b4f-c7f5c34402ed)
5. The button is disabled.

**Expected behavior**
Jump to the next step and receive a comfirmation email. 

**Screenshots**

**Device information (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 127.0.2651.86

**Additional context**

**Comment by melisabok** [comment]
There is a robot validation in that page, please try using another browser. cc @xkopenreview
