### ISSUE TITLE
Adding DBLP link

### ISSUE THREAD

**Issue by VicGutie** [openreview/openreview#212]
**Describe the bug**
I am trying to add my DBLP link to my profile ~Victor_Gutierrez-Basulto1, but it tells me that it is already in use by another profile: ~Víctor_Gutiérrez-Basulto1 (so my name as written with accents). In try to look to see to which email this account is associated but it would seem the account does not exist in OpenReview.

**To Reproduce**
1. Go to edit my profile, add DBLP link 
2. Click on Save Changes
4. See error saying that DBLP link is already used by another profile

**Screenshots**
<img width="1165" alt="Screenshot 2024-08-07 at 04 43 51" src="https://github.com/user-attachments/assets/f4ab5641-3a26-4b5f-a37b-09823f14c28e">

**Device information (please complete the following information):**
 - OS: [e.g. iOS, Windows 10]  Sonoma 
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] 14.5

**Comment by melisabok** [comment]
The profiles have been merged.
