### ISSUE TITLE
"no groups found" error

### ISSUE THREAD

**Issue by TimDettmers** [openreview/openreview#214]
**Describe the bug**
When I want to accept invitations I get a plain page with "no groups found". This happened for two conference.

**To Reproduce**
1. Login
2. Click on an invitations

When I want to accept an invitation from an email
1. Click on link in email
2. Login
3. I see the invitation but the accept and decline buttons are grayed out.

**Expected behavior**
That I can accept invitations.

**Device information (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 127.0.6533.100

**Additional context**
The error also happens in Safari.

I think I have two accounts. I recently changed my email address. I did not get a merge request. I think I would not have seen the invitation if it had gone to the second account.

**Comment by carlosmondra** [comment]
Hello @TimDettmers,

If this issue has not been resolved yet, can you send us an email to info@openreview.net? Thanks

**Comment by carlosmondra** [comment]
This was the correct answer. Feel free to add more context:
> the page has a Cloudflare turnstile widget to avoid bot.
do you have any browser add-on which may have blocked the widget?
the invitations were accepted on your behalf for now.

The issue has been fixed. Thanks for getting in touch with us via email.
