### ISSUE TITLE
No review task despite getting notifications to review

### ISSUE THREAD

**Issue by SolalPirelli** [openreview/openreview#215]
**Describe the bug**
On my OpenReview account (emails firstname dot lastname at {gmail.com, epfl.ch}), I got one notification on Aug 15 and one reminder on Aug 27 to review a paper for "JSys - August 2024".

However, this link does not lead me to a place where I can review, I have no "tasks" in my account nor on the journal's Reviewer Console (which I do have access to).

**To Reproduce**
I don't know exact steps to get in this seemingly-broken state, it may have to do with the fact that I only had an account with my epfl.ch email address, then added my gmail.com address after getting the original notification.

**Expected behavior**
The notification's link to provide a review should have a way for me to submit a review, or at least I should have an assigned task.

**Device information (please complete the following information):**
 - OS: Windows 11 23H2
 - Browser: Edge 128 and Firefox 129

**Comment by carlosmondra** [comment]
Hello @SolalPirelli 

It seems the venue organizers did not run the review stage. Please get in touch with them. 
Also, please avoid sharing personal information here. 

Let me know if you have other questions. I will close this issue.
