### ISSUE TITLE
Message authors from "submission status" tab on the program chair console

### ISSUE THREAD

**Issue by adinriv** [openreview/openreview#216]
**Is your feature request related to a problem? Please describe.**
It is unintuitive to message the authors of a submission by going through the author group, and not having the option to send messages through the submission tab where one will message other actors (e.g., reviewers and ACs).

**Describe the solution you'd like**
- Go to the "submission status" tab on the program chair console
- Select the submissions by clicking on the checkboxes
- Click the message button
- Select the option "Authors of selected submissions" 

**Describe alternatives you've considered**
The existing feature (as far as I know), is to go through the Author's group, and send messages from there.  However, I have received complaints from colleagues about how unintuitive that option is given that the submissions are in other part of the interface.

**Additional context**
None.

**Comment by carlosmondra** [comment]
This [feature](https://github.com/openreview/openreview-web/pull/2064) has been implemented. Thanks for creating this issue:
