### ISSUE TITLE
Paper submission summary not shown; An error message instead.

### ISSUE THREAD

**Issue by jtrint** [openreview/openreview#222]
**Describe the bug**

In "Senior Program Committee Console". OpenReview produces the following message instead of showing a submitted paper's submission summary, after clicking the papers title.

{"pageProps":{"statusCode":400,"message":"id must be string (2024-09-21-9625826)"}}

I get this from AAAI'25 submission #10310 and a couple of others.

**To Reproduce**

Go to the Senior Program Committee Console page, and then click the link with the paper's title in the "Submission Summary" column of the list of all papers assigned to a Senior Program Committee member.

**Expected behavior**

A new tab with the paper's reviews should open. 

**Screenshots**

**Device information (please complete the following information):**

Linux, Firefox 129.0.2

**Additional context**
![BUG](https://github.com/user-attachments/assets/109f807e-2b67-46b2-88aa-67158e96a544)

**Comment by carlosmondra** [comment]
Thanks for reporting this issue. We redeployed the web UI. Could you please check if the issue is gone?
