### ISSUE TITLE
Cannot Assign New Reviewers to A Paper

### ISSUE THREAD

**Issue by frank-xwang** [openreview/openreview#223]
**Describe the Bug**  
I am the program chair of a workshop and encountered an issue while attempting to assign new reviewers to a paper submitted to our workshop.

**To Reproduce**  
Steps to reproduce the issue:  
1. Go to 'Reviewers Paper Assignment'  
2. Click on 'Edit Reviewers Assignments'  
3. Click on 'Assignments (20)'

Although the interface shows 20 assignments (figure 1), none of the reviewers were actually assigned to the paper (please refer to figure 2): 
![image](https://github.com/user-attachments/assets/048bef4f-a9a1-4d1d-a349-0db44cb707bd)

![image](https://github.com/user-attachments/assets/2b0001e7-fdbd-4d04-8862-2139253ecee7)

I have also checked the reviewer list, and it confirms that no one is reviewing this paper.

Workshop link: [NeurIPS Workshop](https://openreview.net/group?id=NeurIPS.cc/2024/Workshop/SSL)

Thank you for your help!!!

**Comment by carlosmondra** [comment]
Is this happening for only one paper? If so, can you please send us an email to info@openreview.net with the submission information so that we can look into it?
