### ISSUE TITLE
Profile update.

### ISSUE THREAD

**Issue by jpmarquessilva** [openreview/openreview#224]
**Describe the bug**
I want to add an email address and change my affiliation, and I can't. When I update my profile, I get an error message suggesting changing my DBLP entry.

**To Reproduce**
1. Go to 'Edit Profile'
2. Make changes, including changing affiliation and/or email address
3. Click on update.

**Expected behavior**
I would expect my profile to be updated without an error message.

**Screenshots**

**Device information (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 130.0.1 (64-bit)

**Additional context**
Nothing else.

<img width="1037" alt="Screenshot 2024-09-23 at 09 00 26" src="https://github.com/user-attachments/assets/e22205e3-bdf5-4df5-af5a-2656bb5c0dfb">

**Comment by carlosmondra** [comment]
I have merged your profiles and should be able to update your profile information. Please let me know if you have any other questions.
