### ISSUE TITLE
Can't merge  not confirmed profiles

### ISSUE THREAD

**Issue by artfawl** [openreview/openreview#228]
**Describe the bug**
I created a profile using my own email. Then I saw that it takes two weeks to confirm that profile, so I decided to create a profile with my institution email. But there is no way to "register for OpenReview" this profile because profile with that Full Name already exists and I must to add new email to merge profiles. So I resend Activation link for the first profile, add institution email and get a message to verify this email. In the verification message It is said that to merge profiles I should follow "the link below". I follow that link and it says me "Please login to access /profile/merge?token=***", but I can't login, because Profile is not confirmed. I tried to put the token in the link into "Enter Verification Token" window in Complete Registration form, but it gives me "Error: Token is not valid" message. So how to merge these profiles?

**To Reproduce**
1) Go to OpenReview
2) Click sign up
3) Enter my name
4) Choose account with own email
5) Click send confirmation link
6) Go to email and follow the link in confirmation email
7) Add email of the second profile in "Emails" section
8) Get OpenReview Account Linking - Duplicate Profile Found message on the institution email
9) Follow the link in the message
10) It says "Please login to access /profile/merge?token=***"
11) Cant login in any account because it is not confirmed
12) Try to put token from the link above into "Enter Verification Token" into verification window from item "7"
13) Get message "token is not valid"

**Expected behavior**
Token should be valid or login into account should be possible

**Screenshots**
![Add_email](https://github.com/user-attachments/assets/7cb15039-4b40-47fa-9fb3-241996b39d21)
![email](https://github.com/user-attachments/assets/e071ed05-356a-41af-a8cc-f16a27abb2c4)
![login](https://github.com/user-attachments/assets/d296405d-3dca-4f30-b157-43cbcb456b09)
![error1](https://github.com/user-attachments/assets/7ee1c925-1378-4818-8700-647166181224)
![error2](https://github.com/user-attachments/assets/27146e0f-e5de-48db-a034-9e17d853c279)
![notvalid](https://github.com/user-attachments/assets/6aaf6743-5f91-48ee-8560-989ab3a00119)

**Device information (please complete the following information):**
 - OS: Windows 10
 - Browser OperaGX

**Comment by artfawl** [comment]
Yes, I got such email, but saw it after I started creating accont with institution email, so I can't just add email and must merge accounts. I decided to wait activation of account, but today I got the following message:
`Your OpenReview profile could not be activated for the following reason:
Please add and confirm an institutional email issued by Skolkovo Institute of Science and Technology to your profile. Please make sure the verification token is entered and verified.

Please go back to the sign up page, enter the same name and email, click the Resend Activation button and follow the activation link to update your information.`

So I followed the steps in issue and faced the problem.

**Comment by carlosmondra** [comment]
Can you please finish the activation process for your institutional account? Do not try to add the email from your other rejected account.

**Comment by artfawl** [comment]
Ok, I finished the registration of my institutional  account. So, should I merge accounts now?

**Comment by carlosmondra** [comment]
Thanks, I just merged them for you. I'll close the issue, but let me know if you have any other issues.
