### ISSUE TITLE
Bad gateway error / Error 500

### ISSUE THREAD

**Issue by uahsan3** [openreview/openreview#23]
I tried to accept my reviewer invite and the bad gateway error appears. When I click on login and enter my details, the following error appears "Error: The OpenReview API is currently unavailable, please wait and try again later". When I try to submit this issue via the feedback form, the attached screenshot shows the error. 

Please help. 

<img width="599" alt="Screenshot 2022-04-02 at 5 01 08 PM" src="https://user-images.githubusercontent.com/4751554/161382157-85b1f735-31ce-44af-96f9-65cb68b21850.png">

My device is MacOS with Chrome Version 99.0.4844.84. 

<img width="718" alt="image" src="https://user-images.githubusercontent.com/4751554/161382247-4311a2dc-533d-4a8f-aa0a-b0644e492ddc.png">

I am trying to do this from Pakistan. Not sure if that is playing a role here.

**Comment by melisabok** [comment]
The issue is fixed, please try again.

**Comment by uahsan3** [comment]
Thank you!
