### ISSUE TITLE
Managing/merging my OpenReview accounts

### ISSUE THREAD

**Issue by Jiawei-han** [openreview/openreview#231]
**Describe the bug**

My Open Review account is: https://openreview.net/profile?id=~Jiawei_Han1

It was used my old e-mail: hanj@cs.uiuc.edu

I need to change it to hanj@illinois.edu in order to communicate with a few conference organizers (e.g., get review assignments).

But when I try to update my preferred e-mail from [DELETED].  I encounter difficulties: it says:

"Error: dblp https://dblp.org/pid/h/JiaweiHan.html is already in use by ~Jiawei_Han2. We recommend merging your profile with ~Jiawei_Han2 by following these steps: Openreview Documentation. (2024-10-06-6193095)"

When I try to get into ~Jiawei_Han2, it says:

"The user ~Jiawei_Han2 does not have an active OpenReview profile"

Thus I cannot update my preferred e-mail from [DELETED], and the conference assignment cannot be sent correctly.

Please help.

-Jiawei Han

[DELETED]

**Comment by carlosmondra** [comment]
I believe this has been fixed. If this is not the case, please email us instead and avoid sharing personal information here. If you have more questions, please read the guidelines before posting an issue. Thanks.
