### ISSUE TITLE
Error when updating my profile at OpenReview

### ISSUE THREAD

**Issue by itohamy** [openreview/openreview#232]
**Describe the bug**
When I'm updating my profile, when pressing on "save profile changes", I get the following error:
Error: keywords/7 must NOT have fewer than 1 characters (2024-10-07-9335826)

**To Reproduce**
Go to my profile, try to save changes.

**Screenshots**
<img width="1125" alt="Screenshot 2024-10-07 at 20 47 24" src="https://github.com/user-attachments/assets/9b36966e-3a25-41b2-943e-9e6ac9e911e9">

**Device information (please complete the following information):**
 - OS: iOS
 - Browser chrome

**Comment by carlosmondra** [comment]
This is possibly a bug that has already been fixed. However, some still needs fixing. Go to the expertise section and make sure there are no trailing commas `,`. If there are trailing commas, simply delete them and continue editing the profile. That should hopefully fix the issue.

**Comment by carlosmondra** [comment]
We fixed all the data in the system. Please let us know if you are still having issues.
