### ISSUE TITLE
After registering, you will receive an email, click on the link to enter your personal information, and report an error when submitting

### ISSUE THREAD

**Issue by INDjyt** [openreview/openreview#235]
After registering, you will receive an email, click on the link to enter your personal information, and report an error when submitting
![捕获](https://github.com/user-attachments/assets/79fdec53-600c-4fc7-8dd6-0dfb13e97bd2)

**Comment by carlosmondra** [comment]
If you are still having this issue, please send us an email to info@openreview.net with your account details so that we can look into it. Thanks!
