### ISSUE TITLE
API unavailable when trying to login 

### ISSUE THREAD

**Issue by WYXsb** [openreview/openreview#237]
**Describe the bug**
When I try to login, it gives me the error: "The OpenReview API is currently unavailable, please wait and try again later". This has been going on for one hour

**To Reproduce**

1. Go to 'https://openreview.net/login'
2. Fill in my account and password
3. Click 'login'

**Expected behavior**
I hope that I can login my account .

**Screenshots**
![image](https://github.com/user-attachments/assets/f57940a2-20e0-4568-8b05-2c6c047ec00f)

**Device information (please complete the following information):**
 - OS: Windows 11
 - Browser Edge,Firefox

**Comment by EasonC13** [comment]
Same!

**Comment by K3ats** [comment]
![image](https://github.com/user-attachments/assets/e44a2f8d-89d1-4914-a0e5-dbc175102bba)
same :<

**Comment by OlgaOvcharenko** [comment]
Same!

**Comment by carlosmondra** [comment]
The API is up again. Thanks for reporting the issue.

**Comment by WYXsb** [comment]
Thank you for swift resolution of the bug.
