### ISSUE TITLE
Display Bug in the Committee Members Chat

### ISSUE THREAD

**Issue by Xovee** [openreview/openreview#239]
**Describe the bug**
Conferences like KDD 2025 use a new "Committee Members Chat" tab for reviewers & chairs discussion. However, in my browser, the chat window does not display the texts. When I scroll the sliders, these texts may instantly show like 0.1 seconds and then disappear. 

**To Reproduce**
1. Go the paper page
2. Click the tab "Committee Members Chat"
3. There shows nothing (though I know there should be some since OpenReview sends a lot of emails. 

**Expected behavior**
Should show the reviewers' chat texts correctly. 

**Screenshots**
<img width="1195" alt="Screenshot 2024-10-24 at 12 32 50" src="https://github.com/user-attachments/assets/42519a16-0baf-4806-9c67-7de7a983e2b7">

**Device information (please complete the following information):**
 - OS: macOS Sonoma 14.6.1
 - Browser Safari 
 - Version 17.6

**Additional context**
None.

**Comment by carlosmondra** [comment]
Please feel free to reopen if issue persists.
