### ISSUE TITLE
In the profile section, add "Senior Lecturer" as rank

### ISSUE THREAD

**Issue by ProfDrChaos** [openreview/openreview#242]
Hi there!

When clicking on your profile (EDIT), and navigate to point 5, History (Education & Career History), and then hitting "Position", then among others, one is presented:
- Lecturer
- Assistant Professor
- Associate Professor
- Full Professor

I would like to request to add the Senior Lecturer, which exists in many countries, at least in Australia (big on research! :)), Israel, and most likely in the UK.

I think it's important to add that rank because otherwise one either has to "downgrade" oneself one rank, or upgrade, both of which seems wrong. Here an explanation of the ranks in Australia:
- You start as Lecturer, which, internationally, is the very same as the Assistant Professor (same responsibilities; just the first rank)
- Then you get promoted to Senior Lecturer, which is pretty much the same as the Associate Professor internationally.
- Now it gets weird: After that, we have the Associate Professor, which is roughly comparable to the Full Professor internationally. That's because many don't even become a Full Professor, and the qualifications required to become an Associate Professor are comparable to those required to become a Full Professor in other countries (at least roughly)
- Then, the Australian fourth rank is the Full Professor, which could also be compared to the Full Professor internationally, with the exception that not necessarily every long-career academic becomes a Full Professor as it requires many achievements that not even everybody aims at in the first place. (So it's more like an award of some sort.)

Thus, missing the rank of a Senior Lecturer would mean that the people at that rank either downgrade themselves by one rank (essentially from Assoc. Prof. to Assistant Professor) or upgrade to Assoc. Prof. (which could be interpreted as an upgrade from Assoc. to Full Professor).

You can also just ignore all these explanations :D, but please add that missing rank! A lot of people should be affected (especially since one usually sits at this rank for quite a while).

**Comment by carlosmondra** [comment]
Hello @ProfDrChaos, 

Thanks for your feedback. Even if an option is not presented in the dropdown, you can still add a custom field. Simply type the desired position and click on it from the dropdown.
Please let me know if you have any issues.
