### ISSUE TITLE
Implement a way to request subreviewer

### ISSUE THREAD

**Issue by ProfDrChaos** [openreview/openreview#243]
Hey there!

First of all, note that I do not know whether you already support that feature! I only see the very few venues I'm involved in (which don't have that feature), so maybe by request is literally obsolete. (In other words, maybe your system does support this feature, but the conferences I was involved in did not request/activate it.) But please check carefully in case you do indeed not have that feature yet, as you absolutely need it; in fact, every single conference should have it, it's incredibly weird that "mine" do not.

Since I do not know how much the team reading all this consist of academics who know how reviewing works, I first give a bit of background. I fully understand that this might sounds incredibly stupid, given that you literally make your money by reviewing :D, it feels like explaining a baker how to bake. Yet, maybe the people reading this are "technicians, coders" rather than academics, so I explain it never the less, just to be save. Then, I make my actual request.

- There are reviewer of multiple levels; which all have different names, even depending on what the conference organizers (the program committee) chooses. For what I ask, all these terms are almost irrelevant. I only care for the "lowest level".
- The lowest "default" level is pretty much *always* called "program committee (PC) member". A PC member usually gets a bunch of papers assigned for which he/she has the full responsibility, including taking part in the discussions to find the final outcome of the paper after discussing with the co-PC members. That said, even if one uses "sub-reviewers" (see next point), the PC member still has the main hat on, and must guarantee for the quality of his/her sub-reviewers' reviews and for making sure that they -- or him/herself -- takes part in the final discussion.

Now, since reviewing this "bunch of papers" is often too much (especially for seniors who might have conflicting responsibilities), pretty much every conferences always offers to use "sub-reviewers". They are brought into the system by PC-members, just for those individual papers that they are assigned to. So, say, I, a PC member, have six papers assigned, then for any of those I can assign a sub-reviewer who can write the review in my stead.

I noticed that none of the openReview conferences I ever was involved in supported that. Best case I cried so much (*manually* via chat/comment/mails) that the conference's orga team invited my chosen subreviewer manually into the system as another PC member and assigned that specific paper to him/her. That is however extremely unprofessional (it's not automated) and also "semantically wrong" because that person *isn't* a PC member; he/she has just a single paper (two max), and not a whole bunch like normal PC members. (That's also why conferences usually separate the two when publishing the list of program committee members; they usually list SPCs/ACs, PCs, and "additional reviewers" or the like; as it should be. Yet, openReview -- as far as I can judge, does not support using sub-reviewers automatically. (Again, you might; in which case: Apologies that you have to suffer through this long post pointlessly.^^).

Now, *how* should that be implemented on your end?

I can't say what's the best way to implement that. I guess all one needs is a way for a PC member to add another reviewer instead, while keeping control over that paper (i.e., the PC member should still be able to comment on the paper, and even be able to change the review of his/her subreviewer). This feature should, of course, only be available if the conference "activates" it, as some might be against this feature. (Though I'd argue that every venue should always allow that.)

Again, if that feature already exists and "my conferences" just coincidentally never activated it: sorry for the unnecessary post.

**Comment by carlosmondra** [comment]
Hello @ProfDrChaos, 

Thanks for the thorough explanation. OpenReview is extremely versatile when implementing workflows, so it is up to the venue organizers to request this feature which is currently NOT implemented. The main reason is that the vast majority of venues haven't requested it.

Some large venues have requested similar features that have been implemented in the past like a mentors-mentees program where a more experienced reviewer helped a reviewer who was just starting to review papers. This was used in ICLR at some point, but it was never requested again, so we didn't make it part of the default options to select from.

**Ultimately, it's the venue organizers that need to be convinced to use this feature.** If we get enough requests to implement it, then we will of course.

Best,
Carlos

**Comment by carlosmondra** [comment]
Related to https://github.com/openreview/openreview/issues/93
