### ISSUE TITLE
Reset password issues

### ISSUE THREAD

**Issue by lingcco** [openreview/openreview#250]
After I go to the reset password page, I submit my new password and I get an error:
Error: Activation token is not valid (2024-11-13-2878623)
I've tried it many times, and I have to do it in two days. Can you help me please? 
My email is 21376195@buaa.edu.cn

**Comment by carlosmondra** [comment]
Please read the [guidelines](https://github.com/openreview/openreview/blob/main/CONTRIBUTING.md). You need to send us an email because it requires sharing personal information.
