### ISSUE TITLE
Submission Overwrite Issue on OpenReview Using Chrome on Ubuntu

### ISSUE THREAD

**Issue by bizerfr** [openreview/openreview#255]
**Describe the bug**
When using Chrome to submit a paper, it seems that if the submission tag is open, the system may overwrite another submission inadvertently.

Thank you for looking into this issue. Please let me know if you require any further details to help diagnose the problem.

**To Reproduce**
1.Open the OpenReview website using Chrome.
2.Log in and navigate to the submission page.
3.Open the submission form for one paper (e.g., PAPER 1111).
4.While the submission form is still open, attempt to submit a new PDF for a different paper (e.g., PAPER 2222).

**Expected behavior**
When submitting a new PDF for a specific paper (e.g., PAPER 1111), the update should only apply to the selected paper. Other submissions (e.g., PAPER 2222) also update accordingly.

**Screenshots**
<img width="699" alt="thumbnail_image" src="https://github.com/user-attachments/assets/be334d8e-87a1-4919-8950-0323d85524ea">
<img width="619" alt="thumbnail_image (1)" src="https://github.com/user-attachments/assets/a6739ce9-3177-48cc-a71b-c5d7324335db">
The two papers almost have the same timestamps.

**Device information (please complete the following information):**
 - OS: ubuntu 24.04
 - Browser: Chrome
 - Version: Chrome Version 129.0.6668.100 (Official Build) (64-bit)

**Comment by emily-grabowski** [comment]
I checked the logs, and I do see the two edits that were made on each paper where the same PDF was uploaded for both papers. However, it looks like the requests both came from the same web browser, not from an error in the system in this case.
