### ISSUE TITLE
Revision History only allows for comparison between different post-review-revisions, does not include originally submitted version (ICLR 2025)

### ISSUE THREAD

**Issue by st--** [openreview/openreview#258]
**Describe the bug**
"Revision History" (openreview.net/revisions?id=<paperid>) only includes revisions that were uploaded post-review. Specifically, if the authors only upload a new version once, there will only be a single version available, and "Compare Revisions" does not allow any comparisons (as there is just a single version). With multiple uploaded revisions, I could compare between those, but not the changes from the originally submitted manuscript.

**To Reproduce**
1. Go to a paper under review (you might have to be one of the reviewers)
2. Click on 'Revisions'
3. See that there is no revision corresponding to the original submission
4. Click on 'Compare Revisions'
5. See that you cannot compare to the original submission

**Expected behavior**
Being able to compare all changes since the review to the version originally submitted.

**Screenshots**
Not possible without breaking review anonymity.

**Device information (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 132

**Comment by carlosmondra** [comment]
These settings are up to the venue organizers to decide. Please get in touch with them to adjust those settings.
