### ISSUE TITLE
Website says I haven't indicated if I want the same reviewers despite having selected it

### ISSUE THREAD

**Issue by x-tabdeveloping** [openreview/openreview#261]
**Describe the bug**
I'm trying to submit our paper for the december ACL Rolling Review cycle.
I filled out all relevant fields of the submission, but when I click submit, the website says that I haven't indicated whether I want to have the same reviewer and editor as last cycle.

**To Reproduce**
1. Go to ACL Rolling Review submission
2. Fill out form as resubmission
3. Click on submit

**Expected behavior**
The submission should go through.

**Screenshots**
![image](https://github.com/user-attachments/assets/1f5702be-0b99-4f35-8c84-0fa7a26168cf)
![image](https://github.com/user-attachments/assets/1991e945-3586-4d4b-9923-e19fa07a4672)

**Device information (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 131.0.6778.85

**Comment by haroldrubio** [comment]
Thanks for letting us know. There was a change that was not accounted for when performing this check but it should be fixed now, please let me know if the issue persists.

**Comment by x-tabdeveloping** [comment]
Thanks for the swift response, I'll get back to you as soon as I've tried

**Comment by x-tabdeveloping** [comment]
Yes, it seems to have been fixed, thanks :D
