### ISSUE TITLE
OpenReview API error shown when opening the home page

### ISSUE THREAD

**Issue by habernal** [openreview/openreview#27]
**Describe the bug**
When opening https://openreview.net (simply by typing it into the address bar), the following error is shown

> Error: The OpenReview API is currently unavailable, please wait and try again later

After refreshing the page, it disappears and all works fine.

**To Reproduce**
1. Open your browser (Firefox 99)
1. Type openreview.net in the address bar
1. See error

**Screenshots**
![Bildschirmfoto_2022-04-26_09-47-56](https://user-images.githubusercontent.com/11850778/165249629-5a52b448-4b38-4f41-9572-3a4f3fd2176f.png)

**Device information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 99

**Additional context**
I have an OpenReview account and haven't cleared any cookies.

**Comment by carlosmondra** [comment]
This has been fixed. Please reopen in case the issue arises again.
