### ISSUE TITLE
request: show papers without a bid in the Reviewers Bidding Console

### ISSUE THREAD

**Issue by kaczmarj** [openreview/openreview#31]
**Is your feature request related to a problem? Please describe.**

In the Reviewers Bidding Console, I have difficulty finding papers that I have not bid on. My workflow for bidding is to filter papers based on keywords (i.e., keywords related to my expertise) and bid on papers that match those keywords. After doing this for several search queries, I then go through the list of papers to bid on papers I had not bid on. I find it difficult to go through each page and find papers without a bid.

**Describe the solution you'd like**

In the Reviewers Bidding Console, it would be great to have an option to show papers that you have not bid on. This will make it easier for reviewers to bid on more papers, because they will not have to scroll through multiple pages looking for papers that they haven't yet bid on.

**Describe alternatives you've considered**

An alternative is to leave the interface as it is.

**Comment by melisabok** [comment]
Thanks for the suggestion! I think this is doable, we could create a new tab to show the papers with no bids or add a checkbox in the All papers tab to filter out papers with no bids.

**Comment by xkopenreview** [comment]
changes to show a new tab which contains paper with no bids have been deployed
