### ISSUE TITLE
Remove invalid email.

### ISSUE THREAD

**Issue by ada-shen** [openreview/openreview#36]
**Is your feature request related to a problem? Please describe.**
My email from the last department has expired, but I cannot delete it.

**Describe the solution you'd like**
I want to remove the invalid email.

**Comment by carlosmondra** [comment]
We try to keep institutional emails for conflict detection, profile disambiguation, etc. If an email has expired, you can add a new email and set it as preferred. All emails from OpenReview will be sent to your preferred email address. If you still want to remove the email, you would need to send an email to info@openreview.net and we will remove it for you.
For more information and a step by step guide, you can check our [documentation](https://docs.openreview.net/getting-started/creating-an-openreview-profile/add-or-remove-an-email-address-from-your-profile).
