### ISSUE TITLE
Mail not being sent to preferred email address

### ISSUE THREAD

**Issue by kylemarkwilliams** [openreview/openreview#4]
**Describe the bug**
I have set a preferred email; however, I am still not getting notifications to my preferred email address of review tasks being assigned to me .

**To Reproduce**
1. Go to 'Profile'
2. Set preferred email.

**Expected behavior**
All future email should go to preferred email. In my case I have been assigned reviews but they were not sent to my preferred email - I checked spam as well.

**Comment by carlosmondra** [comment]
Hi Kyle, this isn't a bug in the system. It seems this is related to your account specifically. Could you please email us at info@openreview.net so that we can look into it?
