### ISSUE TITLE
Error: Token has expired. Please log in again.

### ISSUE THREAD

**Issue by DaniloJRezende** [openreview/openreview#40]
**Describe the bug**

Unable to login using chrome (IOS). After entering login details on https://openreview.net/login, I receive an error "Error: Token has expired. Please log in again."
I've reset chrome and cleared cache but problem persists.

**Device information (please complete the following information):**
 - OS: macOS Version 12.5
 - Browser: chrome
 - Version: 104.0.5112.79

Note: I can login with the safari browser. So this seems like a chrome-specific problem.

**Comment by carlosmondra** [comment]
@DaniloJRezende thanks for reporting this. We believe that the issue has been fixed. Do you mind checking now? Thanks!

**Comment by DaniloJRezende** [comment]
Thank you. It is working now.
Best regards
