### ISSUE TITLE
Unable to login to account:  "The OpenReview API is currently unavailable, please wait and try again later"

### ISSUE THREAD

**Issue by seyuboglu** [openreview/openreview#41]
**Describe the bug**
When try to login to my account I see the following error:
"Error: The OpenReview API is currently unavailable, please wait and try again later"
![image](https://user-images.githubusercontent.com/32822771/185460199-ab642fcf-0215-4058-a72c-b2f04689d129.png)

**Device information (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Chrome 
 - Version: 12.3.1 (21E258)

**Comment by carlosmondra** [comment]
Hi @seyuboglu, the API is definitely working.

This is probably because there is an issue with the network. Have you tried from a different network?

**Comment by seyuboglu** [comment]
This is still happening on Chrome. I tried on FireFox and it worked fine. 

I believe the issue has to do with a [CORS browser extension](https://mybrowseraddon.com/access-control-allow-origin.html) I'm using for web development. After I deactivated it, OpenReview login started working again.

**Comment by jgarcke** [comment]
I can confirm, it has to do with the CORS extension. I had the same error, CORS extension on firefox active, after disabling the extension I can login.
