### ISSUE TITLE
Institution Domain 

### ISSUE THREAD

**Issue by Baichenjia** [openreview/openreview#44]
**Describe the bug**
The  Institution Domain cannot be added

**To Reproduce**
1. Go to 'Profile'
2. Click on 'Edit Profile'
3. Scroll down to 'add position'
4. Add a new position "Shanghai AI Laboratory" (https://www.shlab.org.cn/), the Institution Domain "pjlab.org.cn" cannot be added.

**Expected behavior**

**Screenshots**

**Device information (please complete the following information):**
 - OS: [e.g. iOS, Windows 10]

**Additional context**

**Comment by melisabok** [comment]
this issue has been resolved.
