### ISSUE TITLE
Education & Career History for people who do not work at research institution

### ISSUE THREAD

**Issue by HeidiSeibold** [openreview/openreview#48]
**Describe the bug**

In my profile I can only add career steps that are connected to academic positions. I am now an Open Science Freelancer and cannot have that represented in my profile.

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/14146757/195975908-2d78fc22-1260-4877-91d0-c7f94b9269a8.png">

**To Reproduce**
1. Go to 'profile' -> 'Edit profile'
3. Scroll down to 'Education & Career History'
4. Try to add a role that is not an academic role and a domain that is not a research institution. This will not work. Also not adding anything at all will work. This leads to my profile looking like I work at my previous home institution.

![image](https://user-images.githubusercontent.com/14146757/195976017-a985a807-0c16-4699-b97c-b112988547b9.png)

**Expected behavior**

- It would be great if I could select "others" in 'Postions', potentially with the possibilty to clarify.
- Allow for domains to remain empty or for me to be able to add my work website instead.

Other ideas:
- Potentially allow for "Education & Career History" to remain blank.
- Optionally allow people to import their ORCID history instead of filling this out.

**Device information (please complete the following information):**
 - OS: iOS Monterey
 - Browser: Firefox 105.0.3 (64-bit

**Comment by HeidiSeibold** [comment]
I'd be happy to see if I can write a pull request if you can point me to the right repository (I can't find it 😬).

**Comment by carlosmondra** [comment]
Hello @HeidiSeibold, thanks for reporting this. It may not be clear, but you can actually type anything in the position field or any other field even if it's a drop-down. The drop-down only contains the most common choices, but you can type anything.

 Please let me know if this does not work and I can investigate.

Currently, only some of our repositories are public. We will soon open source everything. You can read more about that here https://openreview.net/about.

**Comment by HeidiSeibold** [comment]
Thanks for the swift response @carlosmondra.

Putting in a different position works, thanks!

I was struggling a bit with the "domain", but when I remove the `https` it works, too. Was a bit unintuitive for me.

Error
![image](https://user-images.githubusercontent.com/14146757/196101777-caaefea5-a604-4af5-8221-dce24e9c2d45.png)

Fixed
![image](https://user-images.githubusercontent.com/14146757/196102760-4e455d15-a6e9-4a3e-9eb8-09519bdefd46.png)



---

Would be very interested in hearing about your process of open-sourcing, as I help other groups/infrastructures in this process. Will there be a blog post about it? Would you be interested in a podcast interview about OpenReview + open-sourcing? 🤓

**Comment by carlosmondra** [comment]
Hi @HeidiSeibold, I'm glad to hear that you were able to update the profile and thank you for the feedback. We are looking at ways to make this more intuitive, so your response is very helpful. 

> Would be very interested in hearing about your process of open-sourcing, as I help other groups/infrastructures in this process. Will there be a blog post about it? Would you be interested in a podcast interview about OpenReview + open-sourcing?

That sounds very interesting! I can get in touch with you via email so that I can copy in the thread the rest of the team.

I will close the issue, but feel free to reopen it or create a new issue if you find something else that needs to be reported.
