### ISSUE TITLE
Meta tag "citation_journal_title" missing for accepted TMLR papers

### ISSUE THREAD

**Issue by Wenlin-Chen** [openreview/openreview#51]
**Describe the bug**
Google Scholar cannot properly index accepted papers at Transactions on Machine Learning Research (TMLR) due to a missing meta tag "citation_journal_title" on their OpenReview webpages.

**To Reproduce**
1. Go to an accepted TMLR paper's OpenReview page (e.g., https://openreview.net/forum?id=8GvRCWKHIL).
2. View page source and notice that the "citation_journal_title" meta tag is missing.
3. Search that TMLR paper on Google Scholar (e.g., https://scholar.google.co.uk/scholar?cluster=17346919672816537199&hl=en&as_sdt=0,5).
4. See that the TMLR version of the paper isn't indexed.

**Expected behavior**
For each accepted paper at TMLR, add a meta tag
`<meta name="citation_journal_title" content="Transactions on Machine Learning Research">`
to its OpenReview webpage according to https://scholar.google.co.uk/intl/en/scholar/inclusion.html#indexing

**Comment by melisabok** [comment]
Thanks for reporting this, we haven't used "citation_journal_title" for any of the other venues before. I believe we would need to set this tags for all the submissions coming from conferences (ICLR) or journals (TMLR).

**Comment by Wenlin-Chen** [comment]
> Thanks for reporting this, we haven't used "citation_journal_title" for any of the other venues before. I believe we would need to set this tags for all the submissions coming from conferences (ICLR) or journals (TMLR).

For conferences like ICLR, you're using the "citation_conference_title" meta-tag which can be correctly indexed by Google Scholar:
`<meta name="citation_conference_title" content="International Conference on Learning Representations"/>`
For TMLR, neither "citation_conference_title" or "citation_journal_title" is used, which I believe caused the indexing problem.
