### ISSUE TITLE
Cannot receive email

### ISSUE THREAD

**Issue by rzhangbq** [openreview/openreview#52]
**Describe the bug**
I want to sign up my email ( [rzhangbq@cse.ust.hk](mailto:rzhangbq@cse.ust.hk) ). I enter my email and submit the form, informing me that I should get an email about confirmation. This email does not arrive.

**To Reproduce**
1.Go to "https://openreview.net/login"
2.Enter email
3.Click on "Didn't receive email information?"

**Expected behavior**
An email should arrive in my inbox with long tokens.

**Screenshots**
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/82951500/200342289-7353b91f-193d-4cae-b18a-95299e942664.png">

**Device information (please complete the following information):**
- OS: [macOS]
- Browser [Microsoft Edge]
- Version [Version 107.0.1418.35 (Official build) (x86_64)]

**Additional context**
The email address was set up recently. It seems that before we set up the email address, we have tried to receive email from your system. Because the email address was not set up then, our school email server might have responded with an "email address not available error". As a result, your system might have marked our email as invalid, therefore refuse to send emails to our address.

The same issue also happens to another email address:[ywanglu@cse.ust.hk](mailto:ywanglu@cse.ust.hk).

Could you please help us check this issue?

Thanks!

**Comment by rzhangbq** [comment]
Hi, thanks for your reply. Our another author, WANG Yumeng ([ywanglu@cse.ust.hk](mailto:ywanglu@cse.ust.hk)) is facing the same issue. Could you also send her confirmation email to her ( through [ywanglu@connect.ust.hk](mailto:ywanglu@connect.ust.hk) )?

Thanks a lot!

**Comment by melisabok** [comment]
We already replied to them! thank you.

**Comment by rzhangbq** [comment]
Thanks!

From: Melisa Bok ***@***.***>
Date: Monday, 7 November 2022 at 2:04 PM
To: openreview/openreview ***@***.***>
Cc: rzhangbq ***@***.***>, Author ***@***.***>
Subject: Re: [openreview/openreview] Cannot receive email (Issue #52)

We already replied to them! thank you.

**Comment by jiazhiguan** [comment]
> We already replied to them! thank you.

Hi, we had the same problem resetting the password for this account [zhaoyoujian@tsinghua.edu.cn].
Could you help us?
