### ISSUE TITLE
Importing the publication list by the other source, such as google scholar.

### ISSUE THREAD

**Issue by HuangChiEn** [openreview/openreview#53]
**Is your feature request related to a problem? Please describe.**
We are always frustrated when the DBLP miss some publication list what the other resource have. Moreover, manually upload about 30 missing meta information of the publication is tedious and not like the engineer working style.

**Describe the solution you'd like**
The most streight forward solution will be provide *Add Google Scholar Papers to profile*, *Add Semantic Scholar Papers to profile*, ...etc buttom. 

**Describe alternatives you've considered**
Moreover, manually upload about 30 missing meta information of the publication is tedious and not like the engineer working style.

Any suggestion will be appreciated!!

**Comment by melisabok** [comment]
Google Scholar doesn't provide an API that we can use to support this feature.

**Comment by HuangChiEn** [comment]
> Semantic Scholar Papers

i see, thanks for your reply. 
fortunately i didn't publish so much paper, lol ~
