### ISSUE TITLE
Problem with signup for CVPR

### ISSUE THREAD

**Issue by lovellbrian** [openreview/openreview#54]
**Describe the bug**

**To Reproduce**
1. Request signup via lovell@itee.uq.edu.au
2. Respond to email
   Please click on the link below to complete your signup for the OpenReview account [lovell@itee.uq.edu.au](mailto:lovell@itee.uq.edu.au).
    https://openreview.net/profile/activate?token=de809187e43ac1c816baa375bf376575e11854da6dd6eb5cb4fc8c3c047e0112
4. Submit signup form
5.  **Error: username ~Brian_C._Lovell1 is not a member of ~Brian_Lovell1**

**Expected behavior**
I would expect to be signed up
**Screenshots**

**Device information (please complete the following information):**
 - OS: [e.g. iOS, Windows 10]  Windows11
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 106.0.3

**Additional context**
I have published under Brian Lovell and Brian C Lovell.  I would have expected these names to merge. 

Thank you

![image](https://user-images.githubusercontent.com/3961718/200539188-5ecc8275-2052-41ba-8c0f-112cc1f52ec0.png)

**Comment by carlosmondra** [comment]
This issue was resolved by contacting us at info@openreview.net
Please feel free to reopen if the same issue arises again.

**Comment by rfabbri** [comment]
Same issue username ~Ricardo_Fabbri2 is not a member of ~Ricardo_Fabbri1

**Comment by melisabok** [comment]
Hi @rfabbri , I found your case and it should be fixed now, can you please try again?
