### ISSUE TITLE
Problem: the two email addresses cannot be associated with the same account. I applied for an Openreview account with the previous email address. I changed the email address before submitting the paper. The new email address could not receive the confirmation email during the registration process. So, I want to associate the new email address with the original email address to the same account.

### ISSUE THREAD

**Issue by zyz111** [openreview/openreview#57]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device information (please complete the following information):**
 - OS: [e.g. iOS, Windows 10]

**Additional context**

**Comment by melisabok** [comment]
Please send us an email at info@openreview.net with the details so we can check your profiles. Thanks.
