### ISSUE TITLE
Error when registering

### ISSUE THREAD

**Issue by aseema** [openreview/openreview#60]
**Describe the bug**
I tried to register, and get an error message "Error: username ~Aseem_Agarwala2 is not a member of ~Aseem_Agarwala1" that I cannot figure out how to resolve

**Additional context**
The system has two emails for me (one corporate, one personal)  that might be causing an issue.

<img width="945" alt="image" src="https://user-images.githubusercontent.com/5631294/201233734-683f8fee-6c20-4b28-8f6f-6dabf368abdf.png">

**Comment by carlosmondra** [comment]
Hi @aseema, thanks for reporting this. Can you try again now?

**Comment by aseema** [comment]
It worked now, thanks!

**Comment by rfabbri** [comment]
Same issue: username ~Ricardo_Fabbri2 is not a member of ~Ricardo_Fabbri1
