### ISSUE TITLE
TokenExpiredError

### ISSUE THREAD

**Issue by jeisner** [openreview/openreview#61]
**Describe the bug**
When I try to click through to a PDF, I get an error.  I am having this problem with multiple papers, on both Linux and Windows, and both when logged into OpenReview and when not logged in. 
```
{"name":"TokenExpiredError","message":"Token has expired. Please log in again.","status":401,"details":{"reqId":"2022-12-01-790658"}}
```

**To Reproduce**
1. Go to https://openreview.net/forum?id=FPCMqjI0jXN
2. Click on the PDF icon
3. See error

**Expected behavior**
The PDF should render.

**Device information (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 107.0.5304.123 

**Additional context**
Logging out and logging in again (as suggested by the error message) does not fix the problem.

**Comment by melisabok** [comment]
Hi @jeisner , could you try to remove the cookies of the browser and try again. 

Let us know if the issue persists.

**Comment by jeisner** [comment]
Removing the cookies for openreview.net indeed fixes the problem.

Still seems like a bug.  Until it's fixed, perhaps change the error message from
"Token has expired. Please log in again." 
to something like this?
"Token has expired. Please log in again. If the problem persists, try clearing your browser cookies for this site."

**Comment by melisabok** [comment]
Thanks for the recommendation! I'm glad that it worked. 

We are aware of this issue, other users reported the same problem and we are working on a fix.

**Comment by melisabok** [comment]
Closing this issue, re-open if the error occurs again.
