### ISSUE TITLE
Crash when editing position title

### ISSUE THREAD

**Issue by odelalleau** [openreview/openreview#62]
**Describe the bug**
`Error undefined` when editing position in profile, when typing the same text that was there before.

**To Reproduce**
1. Go to Profile / Edit Profile
2. Click on any existing position name to edit it (create one first if needed)
3. Type the exact same position name that was there before
4. See error `Error undefined` as soon as you type the last letter

**Expected behavior**
Should not crash.

**Device information (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome (up-to-date)

**Comment by melisabok** [comment]
Thanks for reporting this, the issue must be related to some corrupted data in your profile, could you send us an email at info@openreview.net with your profile id and we can investigate?

**Comment by odelalleau** [comment]
> Thanks for reporting this, the issue must be related to some corrupted data in your profile, could you send us an email at [info@openreview.net](mailto:info@openreview.net) with your profile id and we can investigate?

Sure -- email sent!

Additional precision: it only crashes when the position is a "custom" one that is not within the default list of positions.
