### ISSUE TITLE
OpenReview Dev Site Error: "Bad Gateway"

### ISSUE THREAD

**Issue by LennartPurucker** [openreview/openreview#63]
**Describe the bug**
When trying to sign up for OpenReview's dev site, I get the error "Bad Gateway" and cannot sign up. 

**To Reproduce**
1. Go to https://dev.openreview.net/signup
2. Enter your name and/or e-mail

**Expected behavior**
I should be able to press the sign-up button and register an account. 

**Screenshots**
![image](https://user-images.githubusercontent.com/87503443/210748812-b989eef0-fbb5-413b-90c6-80a037baa614.png)

**Device information:**
 - OS: Windows 10
 - Browser Chrome, safari
 - Version 108

**Additional context**
I was also told by peers that they were able to sign up at some point but did not receive an e-mail later on.

**Comment by carlosmondra** [comment]
Thanks for reporting this. The issue should be fixed now.

**Comment by LennartPurucker** [comment]
Works, thank you very much!
