### ISSUE TITLE
Dev Site "OpenReview signup confirmation" Email Missing

### ISSUE THREAD

**Issue by LennartPurucker** [openreview/openreview#64]
**Describe the bug**
A colleague and I have not received the "OpenReview signup confirmation" Email for the OpenReview Development Site.
We tested it multiple times with different e-mails and waited 8+ hours. 
Moreover, I added "noreply@openreview.net" to my contacts. 

**To Reproduce**
1. Go to https://dev.openreview.net/signup
2. Sing up

Or
1. Go to https://dev.openreview.net/login
2. Enter the already signed-up email.
3. Click "Didn't receive email confirmation?"

**Expected behavior**
You should receive an email to register an account on the dev site. 

**Device information:**
- OS: Windows 10
- Browser Chrome
- Version 108

**Comment by carlosmondra** [comment]
Hello @LennartPurucker, the dev site does NOT send emails. In order to activate your account, you need to request the activation link at info@openreview.net.

**Comment by carlosmondra** [comment]
Thanks for pointing this out! You did not misunderstand anything. I'll make sure that we update the documentation with all the details.
