### ISSUE TITLE
fix name and ID

### ISSUE THREAD

**Issue by feamster** [openreview/openreview#65]
**Describe the bug**
My name and ID are incorrect.

**To Reproduce**
1. Go to https://openreview.net/profile?id=~Nicholas_Feamster2
2. See error.

**Expected behavior**

1. Name should be Nick Feamster
2. ID should be Nick_Feamster
3. Affiliation should be University of Chicago

**Additional context**

I'm not familiar with your system, so it's not even clear how to log in to fix this.

**Comment by feamster** [comment]
I tried to log in to claim the profile with Nick Feamster (for which there are already publications) but it won't let me because it says my email address at UChicago is associated with another user ID. Please delete the other user IDs and make Nick_Feamster the primary. Thank you.

**Comment by melisabok** [comment]
please send us an email at info@openreview.net with your email address associated with another user ID and we will take a look, thanks. Melisa

**Comment by melisabok** [comment]
I see there are different profiles that must be merged:

https://openreview.net/profile?id=~Nick_Feamster1
https://openreview.net/profile?id=~Nicholas_Feamster1
https://openreview.net/profile?id=~Nicholas_Feamster2

Could you confirm the three of them show data associated with you, if that is the case then I can merge all the profiles.

**Comment by feamster** [comment]
@melisabok They are indeed all me.  I did try to register one of them, but the only name I publish under is Nick.

Thank you!

**Comment by melisabok** [comment]
Hi Nick,

All the profiles were merged: https://openreview.net/profile?id=~Nick_Feamster2

It seems one of the profiles was active so you just need to login or reset your password. 

Best,

Melisa

**Comment by feamster** [comment]
Awesome, thanks! I just activated.  I've also requested deletion of "Nicholas" in the profile. Never published under that name. Thanks!

**Comment by melisabok** [comment]
Approved!
