### ISSUE TITLE
I am not getting notifications for assigned to review papers

### ISSUE THREAD

**Issue by papachristoumarios** [openreview/openreview#66]
**Describe the bug**

I am not getting notifications for assigned to review papers.

**To Reproduce**

I accepted an invitation to become a reviewer at a conference that uses openreview.

**Expected behavior**

Get email notification when a paper is assigned to be reviewed.

**Comment by melisabok** [comment]
Please send us an email at info@openreview.net and we will investigate your case.

Thanks,

Melisa

**Comment by carlosmondra** [comment]
Closed due to inactivity. If the issue persiste, please send an email to info@openreview.net
