### ISSUE TITLE
API unavailable when trying to sign up

### ISSUE THREAD

**Issue by quantagenmtg** [openreview/openreview#68]
**Describe the bug**
When I try to sign up it gives me the error: "The OpenReview API is currently unavailable, please wait and try again later". This has been going on for the last 5 hours

**To Reproduce**
1. Go to 'https://openreview.net/signup'
2. Fill in details
3. Click 'sign up'
4. Confirm and click 'register'

**Expected behavior**
Expected the creation of my account

**Screenshots**
![Capture](https://user-images.githubusercontent.com/76404652/225785790-b2483be6-84ab-40bb-81c4-acd77e65cbb4.PNG)

**Device information (please complete the following information):**
 - OS:  Windows 10
 - Browser: tried Safari, Chrome and Firefox

**Additional context**

**Comment by melisabok** [comment]
Could you please try again and let us know if the error persists?

Thanks,

Melisa

**Comment by quantagenmtg** [comment]
Hi Melisa,

I still get the same error.

Kind regards,
Lionel

**Comment by melisabok** [comment]
Our API doesn't report any down time issues. 

Could you try using another internet connection?

If there error persists, please send us an email at info@openreview.net with the full screenshot and we will take a look.

**Comment by melisabok** [comment]
Apologies for this. We identified the issue related to an API rate limit configuration. 

Could you please try again?

Best,

Melisa

**Comment by quantagenmtg** [comment]
Works now, thank you!
