### ISSUE TITLE
Adding a "Mark all notifications as read" button

### ISSUE THREAD

**Issue by Pseudomanifold** [openreview/openreview#69]
Thanks for providing OpenReview and this great way for reporting potential issues. An active project like this with a good feedback channel is rare and should be treasured :smile: 

**Is your feature request related to a problem? Please describe.**

Numerous interactions on OpenReview result in a notification. All these notifications are shown under the "Notifications" button in the main web interface, but I find no way of "marking all notifications as read" or something.

**Describe the solution you'd like**

A button "Mark all as read" or a way to select multiple notifications at once would be great.

**Describe alternatives you've considered**

I tend to ignore the notifications altogether, which is bad, or have to click through all of them manually, which is somewhat tedious.

**Additional context**

35 notifications, without a way to go through them:

![image](https://user-images.githubusercontent.com/11440811/227149560-a659760b-22ef-46b6-9812-5527b16d5ff1.png)

**Comment by carlosmondra** [comment]
Thanks for your feature request.

A Mark All as Read button has been implemented. Feel free to add more comments regarding this even if the issue  is closed.

**Comment by Pseudomanifold** [comment]
Amazing, I already see it in my console :exploding_head:! Thanks so much! :heart:
