### ISSUE TITLE
Unable to receive email

### ISSUE THREAD

**Issue by LHH-chuang** [openreview/openreview#75]
I am Li Haohan, a graduate student at Hangzhou Dianzi University. My campus email is [EMAIL REMOVED] Unable to receive registration email when registering information. I don't know the specific reason. I hope you can check it out.

**Comment by melisabok** [comment]
The email can not be delivered because of the status "Bounced Address" , please send us an email to info@openreview.net and we can share the confirmation link with you.

**Comment by xxllp** [comment]
chinese email  can not receive email ,but my gmail can't receive too

**Comment by carlosmondra** [comment]
We haven't received other reports of users not receiving emails in their gmail accounts. If this issue is still happening, please send us an email to info@openreview.net since this requires you to share personal information. Thanks.
