### ISSUE TITLE
Cannot access my reviewer tasks

### ISSUE THREAD

**Issue by Elbtity** [openreview/openreview#77]
I have a problem accessing my reviewer tasks. Please find the attached screenshot for the error: 
<img width="436" alt="OpenReview issue" src="https://user-images.githubusercontent.com/7956540/235333161-439b2d05-6d03-4fdc-95e2-f155530ad4d4.PNG">

**Comment by racheljsmart** [comment]
Hello,

I believe this issue is resolved and you should have access to your assigned paper. If you continue to have issues, please contact us via info@openreview.net

-Rachel
