### ISSUE TITLE
Add fields for contrubtions to the Academic Computer Science Body of Knowledge by participants from industry

### ISSUE THREAD

**Issue by roynielsen17** [openreview/openreview#78]
**Is your feature request related to a problem? Please describe.**

I would like to request a feature: Under Education and Career History, you allow for non-academic professional experience to be listed.  I couldn't figure out how to add professional experience that could add to the domain knowledge of academic field of computer science from places like Los Alamos National Laboratory, Alpenglow Biosciences, Pennsylvania State University, Intel as well as others.  Their knowledge, research, experience is no less useful to the Academic Computer Science Body of Knowledge, than those in academia alone.  I believe the same rigor of review for conflict of interest and ethics applies to those from industry as it does from academia, but I think the field could benefit from hearing from those with applied knowledge, just as the field of Physics has a sub-category, or sister category of Applied Physics.

**Describe the solution you'd like**

Possibly allow for a few "Other" or "Industry" fields, and allow for people that wish to contribute to the Academic Computer Science Body of Knowledge, that have valid experience in researching, integrating, architecting, developing, testing, implementing, and/or managing systems that fall in the Academic Computer Science Body of Knowledge.

**Describe alternatives you've considered**

I do not see an alternative to allow for people using this system to see and/or understand the background of people that have participated in startups, government research. laboratories, universities, in professional capacities. 

I'm happy to describe research projects, etc that I have participated in at those organizations under the research section, but if you allow people who have spent most of their career in Industry, via professional career tracks - you should allow for their associations with those organizations to be listed in the same or similar method you use to identify what academic institutions people on a purely academic track use to record their associations.

**Additional context**

I am currently disabled, and cannot participate in furthering my education or participating in the professional sphere, but I can write.  I have more than a couple of decades of experience in the fields of Computer Science and Electrical Engineering that could yield value, either as a reviewer, or as a participant in sharing and contributing to the Academic Computer Science Body of Knowledge.

I look forward to your triage and disposition of this feature request.

**Comment by racheljsmart** [comment]
Hello Roy,

Thank you for your detailed feedback and explanation of the desired feature request. 

Currently, the Education & Career History section contains free text fields that allow users to type in their Position, Domain, and Institution Name if they are not present in the suggested list. Institution in this context can refer to any organization, not exclusively academic. We do have users who list their labs, companies, and research projects in the Education & Career History section. We use this section for conflict of interest detection when we do paper matching.

Would it be helpful if we elaborated or provided examples in the description to encourage the inclusion of professional experience in these free text fields? If I am misunderstanding your request, please let me know.

Best,
Rachel
