### ISSUE TITLE
Authors can't see reviews of their papers after Decision stage.

### ISSUE THREAD

**Issue by anasfkhan81** [openreview/openreview#80]
**Describe the bug**

Authors of papers cannot see reviews. The Decision stage is closed, we have sent out mails via the Post Decision Stage button. These have arrived and the decisions themselves are visible but the reviews still can't be seen at {{forum_url}}. We have gone through the settings in the configuration page as readers/chairs and we cannot work out what is the issue. 

**To Reproduce**

Author of submission clicks on the URL {{forum_url}} in the post decision mail which was sent out. They see the decision but not the reviews themselves. 
 
**Expected behavior**
For the reviewer to see the review. 

**Screenshots**

**Device information (please complete the following information):**
 - OS: [e.g. iOS, Windows 10]
Windows 10

**Additional context**

**Comment by anasfkhan81** [comment]
Dear Melissa,
We tried doing this but received the following error when running the
review stage again:

{
  "name": "MissingError",
  "message": "The field title is empty or missing",
  "status": 400,
  "details": {
    "path": "content.title",
    "reqId": "2023-05-05-665564"
  }
}

**Comment by melisabok** [comment]
Could you share the venue id  or the venue request form url?

**Comment by anasfkhan81** [comment]
Here it is https://openreview.net/forum?id=APA5Z7TG11

**Comment by melisabok** [comment]
It seems the review invitation was out of sync with "Review Stage" settings, fields like rating and confidence were defined differently. I fixed it and the reviews are visible to the authors now.

**Comment by anasfkhan81** [comment]
Hi, now the decisions seem to be invisible to the authors. Could you help us with this? (I don't want to change something and create another error)

**Comment by melisabok** [comment]
I replied this in another email.

The decisions can be revealed to the authors if you go to the decision stage and select "Yes, decisions should be revealed when they are posted to the paper's authors"

**Comment by anasfkhan81** [comment]
this seems to work (in the sense that authors can now see decisions) but it  brought up another error (with the reference https://api.openreview.net/references?id=8qvStwCkY): 
{
  "name": "NotMatchError",
  "message": "The value 0: Borderline in field rating does not match the invitation definition",
  "status": 400,
  "details": {
    "path": "content.rating",
    "value": "0: Borderline",
    "expected": [
      "10: Top 5% of accepted papers, seminal paper",
      "9: Top 15% of accepted papers, strong accept",
      "8: Top 50% of accepted papers, clear accept",
      "7: Good paper, accept",
      "6: Marginally above acceptance threshold",
      "5: Marginally below acceptance threshold",
      "4: Ok but not good enough - rejection",
      "3: Clear rejection",
      "2: Strong rejection",
      "1: Trivial or wrong"
    ],
    "reqId": "2023-05-05-1820516"
  }
}

**Comment by melisabok** [comment]
this was me trying to fix rating field. It seems you edited the invitation without using the review stage and the data was out of sync, I fixed it here: https://api.openreview.net/references?id=DroFq2cEP

there should no errors now.

**Comment by anasfkhan81** [comment]
everything seems to be resolved now....thanks for all your help!
