### ISSUE TITLE
Last name 20 character limit

### ISSUE THREAD

**Issue by 3f6a** [openreview/openreview#81]
Hello, I have a long composite last name which I use to sign papers. What's the reason behind the 20 character limit in the last name field of the profile?

**Comment by carlosmondra** [comment]
Hello, thanks for reporting this. How many characters does your composite last name have?

**Comment by 3f6a** [comment]
24 characters. Is there a reason to have a limit at all?

**Comment by carlosmondra** [comment]
Thanks for your answer. Yes, we try to protect every field as much as possible so that they are not abused. In cases like this, we need to make adjustments, of course.

**Comment by carlosmondra** [comment]
@3f6a this has been fixed.
