### ISSUE TITLE
Inability to write curly braces inside math equations in Abstract in OpenReview platform.

### ISSUE THREAD

**Issue by burlachenkok** [openreview/openreview#85]
The OpenReview platform during filling the Abstract for conference submission does not support either inline math mode or in display mode left or right curly braces:
 ```$\left\{$``` or ```$\right\}$``` or  ```$\{\}$```.

From another side it supports ```$\left\[ \right.$, $\left\( \right.$, $\left\( \right.$, $\{\}$```

Unsupported curly braces are not good, because it's a pretty standard mathematical symbol: https://www.overleaf.com/learn/latex/Brackets_and_Parentheses

Please fix it if you agree. In case the problem is not on your side but in the implementation of TEX/Latex which you use (MikTex, TeX Live, MacTeX, teTeX, proTeXt) forward this bug to them.

**Comment by zbialecki** [comment]
@burlachenkok It seems like you might have forgotten to escape your backslashes when inputting your TeX markup into the submission form. OpenReview supports both TeX for mathematical notation and Markdown for formatting text, but one side effect of this is that all backslashes in TeX need to be replaced with `\\`.  You can try this out by copying the following examples into the text area. 

```
$\\{ x+y \\}$

$$ 
F = G \\left( \\frac{m_1 m_2}{r^2} \\right)
$$
```

For more information, please see the our docs page on TeX support: https://docs.openreview.net/reference/openreview-tex/openreview-tex-support

**Comment by burlachenkok** [comment]
Thanks @zbialecki very much. This combination `$\\{123\\}$` works, and `$\\left\\{ 123 \\right\\}$` as well. Let's close a ticket.
