### ISSUE TITLE
Impossible to verify former emails

### ISSUE THREAD

**Issue by Guillaume-Garrigos** [openreview/openreview#87]
The current policy of OpenReview is to ask user to give their former email adresses, to help identify duplicate users, as indicated by the following text : 

```
Emails associated with former affiliations (including previous employers) should not be deleted. 
This information is crucial for deduplicating users and ensuring that you see your reviewing assignments. 
OpenReview will only send messages to the address marked as “Preferred”.
```

But when a user enter an old email from a former affiliation, an email is sent to the said address for verification. The big problem is that most of the time, institutions delete the account associated to an email when the person leave the institution. This makes the email verification impossible.

Since OpenReview declares that `OpenReview will only send messages to the address marked as “Preferred”` , I believe that only the preferred address should be verified as a valid email. The other emails are only there on a declarative basis, serving a deduplicating purpose.

**Comment by Guillaume-Garrigos** [comment]
I believe you, but upon entering my old address, I had a message telling me that I would receive an email on this (dead) address. I think that this behavior 1) could be stressful to people, making them believe they are doing something wrong, with an impossibility to access their dead email addresses 2) could incitate people to not put at all their old addresses (opposite of your objective) because they don't want to do something wrong.

Just my opinion!

**Comment by melisabok** [comment]
Hi Guillaume,

> I had a message telling me that I would receive an email on this (dead) address

Who sent you the message? that's not true, OpenReview only send emails to preferred email addresses.
