### ISSUE TITLE
Area Chair console shows zero ratings and confidences

### ISSUE THREAD

**Issue by habernal** [openreview/openreview#9]
**Describe the bug**

In the "Area Chair Console" for ARR (ACL rolling review), only zeros are shown for paper scores and confidences; see the screenshot.

![Bildschirmfoto_2022-02-16_17-08-57](https://user-images.githubusercontent.com/11850778/154307314-98879aa0-f078-4a4f-b5bc-34aadf997059.png)

**Comment by melisabok** [comment]
Thanks for reporting this, could you tell us which ARR cycle you are an AC?

**Comment by nlbahy** [comment]
Fixed!
