### ISSUE TITLE
incorrect id name

### ISSUE THREAD

**Issue by jiangzhengkai** [openreview/openreview#94]
**Describe the bug**

I want to change my account id https://openreview.net/profile?id=~Zhengkai_Jiang3 to https://openreview.net/profile?id=~Zhengkai_Jiang. Please help me delete number 3 from my personal account.

Why does number 3 appear in id, I only have one name for my personal account.

**Comment by melisabok** [comment]
All the OpenReview profile ids have a number at the end of the name. This number is increased when the name is already being used by another profile.

**Comment by jiangzhengkai** [comment]
@melisabok Current, I have only one name, and the profile id is still 3.

**Comment by jiangzhengkai** [comment]
@melisabok I search the profile id 1 and 2, but nobody is using these profiles.

**Comment by melisabok** [comment]
Those profile exists but they are not public or not yet claimed.

**Comment by jiangzhengkai** [comment]
@melisabok I think both id 1 and id 2 are myself. I used to have three id names and delete two, thus can you help me delete 1 and 2?

**Comment by jiangzhengkai** [comment]
@racheljsmart Instruct2Act: Mapping Multi-modality Instructions to Robotic Actions with Large Language Model is my paper.

**Comment by jiangzhengkai** [comment]
@racheljsmart Please merge the profiles into one

**Comment by jiangzhengkai** [comment]
@racheljsmart Any problem merging the profiles into one?

**Comment by racheljsmart** [comment]
@jiangzhengkai Apologies for the delay, yes ~Zhengkai_Jiang3 and ~Zhengkai_Jiang2 have been merged. 

Previously, there was an all lowercase name included in your profile and the ID ~zhengkai_jiang1 was created. That name was requested to be removed, and was replaced with ~Zhengkai_Jiang3.

**Comment by jiangzhengkai** [comment]
Why not replaced merged profiles with ~Zhengkai_Jiang1, you can also delete the ~zhengkai_jiang1 for this case.

**Comment by racheljsmart** [comment]
The usernames are automatically assigned by the backend in a case-insensitive manner, and unfortunately, we do not have the ability to assign specific usernames as desired.

**Comment by jiangzhengkai** [comment]
Or How can i delete current user name Zhengkai_Jiang3, and restore to first zhengkai_jiang1?

**Comment by jiangzhengkai** [comment]
@melisabok Would you give a solution considering the above request?

**Comment by melisabok** [comment]
Hi @jiangzhengkai, I restored the name ~Zhengkai_Jiang1 and now it is your preferred name: https://openreview.net/profile?id=~Zhengkai_Jiang1

This was an exception and we can not accept more of these kind of changes again.

Best,

Melisa

**Comment by jiangzhengkai** [comment]
@melisabok Thanks
