### ISSUE TITLE
Cannot update profile

### ISSUE THREAD

**Issue by cindyxinyiwang** [openreview/openreview#96]
**Describe the bug**
I want to add a career history to my profile, but when I click on save, it shows an error that "Group name not found  ~Xinyiw_Wang1". I have two names one file, one of which was the wrong name(which I already requested to remove.)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device information (please complete the following information):**
 - OS: [e.g. iOS, Windows 10]

**Additional context**

**Comment by melisabok** [comment]
Hi Xinyi,

I think this was related to an error produced when deleting the name, it should be fixed now. Could you try again?

Melisa
