### ISSUE TITLE
Add explanation how relation in profile is to be interpreted

### ISSUE THREAD

**Issue by jowagner** [openreview/openreview#97]
**Problem**
When entering Phd/Postdoc relationships in the profile, it is not clear whether to pick "advisor" or "advisee" as the profile page does not say whether the relation is to describe my role or the role of the named person.

**Suggestion**
Drop the distinction as the existing data cannot be relied on and the distinction is not required for conflict of interest detection, the purpose of the data collection (I presume; you might want to clarify this in the `/profile/edit` page). Suggested implementation steps:
1. Display both existing "advisor" and "advisee" relations as "advisor/advisee".
2. Add a new relation "advisor/advisee" to the drop-down list.
3. If easy and if it does not cause trouble when editing existing entries, remove the old choices "advisor" and "advisee".
4. Do not allow new entries with "advisor" and "advisee", showing a message to pick "advisor/advisee" from the drop-down list instead.
5. Convert all existing "advisor" and "advisee" entries to  "advisor/advisee"
6. Remove choices  "advisor" and "advisee" if not done in step 3

**Alternatives considered**
Adding a sentence before the table clarifying how to read the relation, e.g. "I am PhD advisor of `name`" or "My PhD advisor is `name`", is not a great solution as the database is already populated with lots of advisor and advisee relationships with unknown interpretation and asking all users to check and update their relation data seems unreasonable, assuming the direction of the relation is not needed. At least, the direction should not be needed for conflict of interest detection.

**Additional context**
How often users choose one or the other interpretation for the direction "I am PhD advisor of `name`" vs "My PhD advisor is `name`" can be estimated by checking a random sample of profiles with publication records and by assuming that more senior authors appear later in the list of co-authors.

**Comment by melisabok** [comment]
You need to describe the position of the relationship you are entering.

**Comment by jowagner** [comment]
The Position is under the heading "Advisors, Relations & Conflicts" on the page https://openreview.net/profile?id=<USERID> and under the heading "Advisors & Other Relations" on the page https://openreview.net/profile/edit

**Comment by xkopenreview** [comment]
Hi
the relations section has a description which states
>Enter all advisors, co-workers, and other people that should be included when detecting conflicts of interest.

so I think it's clear that the relation is describing  the named person instead of the current user.
it can't be changed to advisor/advisee because some conference may choose to take only advisor or only advisee into consideration.

thanks.

**Comment by jowagner** [comment]
OK. I checked 20 profiles in my network: 8 have entered relations the way you anticipate (role = named person), including myself. The remaining 12 have not entered relations or only symmetric relations. While I'd guess that many feel that their conflicts of interest are sufficiently declared through co-authorship in the indexed publications. I can also imagine that some users prefer not to enter any data when unsure how to enter them correctly. That would be good news as it would mean that the existing data in the database can be trusted and more users can be won to enter conflicts by improving the description / providing an example.

**Comment by xkopenreview** [comment]
Hi

thanks for checking.
we will include this issue when we plan for enhancements.

thanks.

**Comment by carlosmondra** [comment]
The following text was included as description:

> For example, you can choose ‘PhD advisor’ and enter the name of your PhD advisor.
