### ISSUE TITLE
paper on openreview is not synchronized in google scholar

### ISSUE THREAD

**Issue by changhongyan123** [openreview/openreview#98]
**Describe the bug**
My paper published at ICLR on openreview was removed by google scholar. I can find it a few days before but it is removed now.

**To Reproduce**
1. Go to 'https://openreview.net/forum?id=V7CYzdruWdm'; you will see the paper
2. Go to 'https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=bias+propagation+in+federated+learning&btnG=&oq=' on google scholar. There are no results related to our paper on openreview

**Comment by melisabok** [comment]
Google Scholar is reporting the papers exists and you can find it here: https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=https%3A%2F%2Fopenreview.net%2Fforum%3Fid%3DV7CYzdruWdm&btnG=

**Comment by changhongyan123** [comment]
Oh, it works now. Thank you so much for your help!

**Comment by changhongyan123** [comment]
Hi @melisabok, 

It is a bit weird but the link you provided is now showing a different paper.

**Comment by changhongyan123** [comment]
Hi @melisabok 

May I know if there is any update on this? Thank you for your help!
