### ISSUE TITLE
Cannot Import Papers from DBLP

### ISSUE THREAD

**Issue by StevenLau6** [openreview/openreview#99]
**Describe the bug**
I was prohibited from selecting my paper after clicking the "Add DBLP Papers to Profile". 
I read the frontend code. The checkbox was disabled, it said "Your name does not match the author list". Because DBLP added 002 after my name, like this one "Shuaiqi Liu 0002", to distinguish people with the same name. 
The system seems do not deal with this issue.

If I delete "disabled", it works. 

![image](https://github.com/openreview/openreview/assets/19513107/7e536fa3-c841-42ed-b292-0c7a720c4d53)

**Comment by xkopenreview** [comment]
Hi Shuaiqi,

thank you for reporting this issue.
the trailing 0002 will not prevent you from importing papers.

the checkboxes are disabled because the last name in your profile is in upper case "LIU" which is different from the name in dblp "Liu"

thanks.

**Comment by carlosmondra** [comment]
Closing as there is no issue here.
